### ISSUE TITLE
scroll to top not working.

### ISSUE THREAD

**Issue by starchild** [victorjonsson/jQuery-Form-Validator#100]
Hi,

I just can't get this to work.  Am using jquery 1.9.1.

We need errors to show on the elements, not at the top.  Not sure if that's the issue.

Thanks a lot.

**Comment by arvindkrkashyap** [comment]
Hi victor, i am having an issue, when i used the cdn path for script jquery-form-validator.js, the pass  comparison validation is working fine, but when i download script to my localhost, and then the pass comparison is not validating. pls help me out

**Comment by victorjonsson** [comment]
Please create a new issue.
