### ISSUE TITLE
onValidate callback function not returning the element and message

### ISSUE THREAD

**Issue by yukimi88** [victorjonsson/jQuery-Form-Validator#104]
Hi, I'm having javascript function to further check some input fields.  I'm using onValidate callback function as per your example:

onValidate : function() {
      return {
        element : $('#some-input'),
        message : 'This input has an invalid value for some reason'
      }
    }

From my understanding, the $('#some-input') will be highlighted as error with error message "This input has an invalid value for some reason", am I correct?  But I'm not getting any response for this function, meaning some-input is not being highlighted as error.  
Secondly, somehow Eclipse marked the syntax as wrong if without closing semicolon in the message property (example above).

Please advise.  Thanks!

**Comment by codingarrow** [comment]
from the http://formvalidator.net/#configuration

The example 

    onValidate : function() {
      return {
        element : $('#some-input'),
        message : 'This input has an invalid value for some reason'
      }

Only applies to a single element, what if I want several elements to validate, I've tried these and it's never possible

      return {
        element : $('#some-input'),
        message : 'This input has an invalid value for some reason'
        element : $('#some-input1'),
        message : 'This input has an invalid value for some reason 1',
        element : $('#some-input2'),
        message : 'This input has an invalid value for some reason 2'

Can you at least demo if this possible?  I've seen no example for this?

**Comment by victorjonsson** [comment]
That is currently not supported but it would be good improvement.

**Comment by victorjonsson** [comment]
This is supported since some releases back. The callback `onValidate` can return an array with error dialogs.

```js
$.validate({
  return [
     {
        element : $('#some-input'),
        message : 'This input has an invalid value for some reason'
     },
     {
        element : $('#some-other-input'),
        message : 'This input also has an invalid value for some reason'
     }
  ]
});
````
