### ISSUE TITLE
jQuery function .append('<form here>') causes no validation.

### ISSUE THREAD

**Issue by bradthedev** [victorjonsson/jQuery-Form-Validator#111]
On my current site i'm adding in rows to a form. This is for invoices so every invoice can have from 1 item to thousands of items. every time i add a row i use the .append() function of jQuery. The form along with the append() has all the validation variables correctly inputted. the first row of the invoice works perfectly until i try to append the next row of the form to it. As soon as i append another row it breaks and allows the form to submit without any validation 

The image below shows how the onBlur is working for the first row but none other. Also from the view of the form in this image if i was to hit submit, even with the validator knowing that the first row is not validated it will still allow the form to POST into the php.

![form](https://f.cloud.github.com/assets/6921761/2388955/8b0c98a4-a947-11e3-801e-5732d8893f54.png)

**Comment by momtazhome** [comment]
@timothe  Please I need Example For using destroy() function

**Comment by timothe** [comment]
@momtazhome simpy put:
`$('#form1').bootstrapValidator();
$('#form1').data('bootstrapValidator').validate();
$('#form1').data('bootstrapValidator').destroy();`

**Comment by momtazhome** [comment]
bootstrapValidator is not a function

**Comment by momtazhome** [comment]
i use jQuery Validation Plugin v1.16.0
