### ISSUE TITLE
Error on Server-Side validation

### ISSUE THREAD

**Issue by webgodo** [victorjonsson/jQuery-Form-Validator#123]
Hi Victor,
I have included your Form Validator plugin in my project on a sign-up form. everything is ok, but I have a field for E-Mail address and I want the validator to validate it on server-side.
the input is like this:

&lt;input type="text" data-validation-url="validate-email.php" data-validation="required email server" value="" name="amail"&gt;

and I have created validate-email.php file as following:

$result = array(
    'valid'   => false,
    'message' => 'some error message from server'
);

echo json_encode($result);

when I want to test it, nothing happens on server-side. on the firebug Console, it gives me an error message:
Using undefined validator "validate_server"

what's the problem?

**Comment by ismaserrano** [comment]
Hey @victorjonsson , although the security module is loaded, the plugin show me 'Using undefined validator "validate_server"'. I don't know if is a server configuration, because the problem appears one day to another day.
I'm feeling lost...

**Comment by ismaserrano** [comment]
Okay, solved! If you concat and minify JS with Grunt, need to load modules in the Gruntfile.js
