### ISSUE TITLE
Server side validation with preset values

### ISSUE THREAD

**Issue by kallevf** [victorjonsson/jQuery-Form-Validator#125]
When using server side validation and already prefilled values (that are valid) the form will validate but it will not submit.

Attached is example code (till me if you want a copy of the actual file). If you hit the Post button without focusing on the field before the form will not submit even if it is valid.

Kalle

![image](https://cloud.githubusercontent.com/assets/5522611/2708735/55d77554-c4af-11e3-8fd2-f28225b06caf.png)

**Comment by kallevf** [comment]
This does not seem to be solved in 2.2 release.
Updated JSfiddle here: https://jsfiddle.net/79be2pqu/
Same issue: form is not submitted if the input field is not blurred before submit.

**Comment by kallevf** [comment]
Currently using this fix to make it work:
$(document).ready(function() {
   setTimeout(function(){$('input[data-validation*="server"], textarea[data-validation*="server"], select[data-validation*="server"]').filter(function() { return $(this).val(); }).blur();}, 500);
});

**Comment by victorjonsson** [comment]
First off. The jsfidde still uses the old version of the plugin. Secondly, I don't get jsfiddle to work at all, I get $ is not defined in the console.... But I have investigated this further and found that the reason why your example doesn't submit the form depends on the name of the input element having type=submit. I know it sounds crazy but it's true. Everything will work as expected as long as you don't have the value "submit" in the name property of the input element with type submit. 

Try it out here: http://jsbin.com/xuxitixora/3/edit?html,output . If you change the name of the submit button to "submit" you will find that the form won't get submitted once validated on the server side. I guess that when jquery-form-validator triggers the second submit jQuery will try to call the native submit-method on the form element but that property is taken by the reference to the input element.

**Comment by kallevf** [comment]
Thank you. Now it works as expected!
