### ISSUE TITLE
Bootstrap 3 display issue (input-group-addon)

### ISSUE THREAD

**Issue by Lickeh** [victorjonsson/jQuery-Form-Validator#126]
Hi,

Small display issue I don't know if anyone can help with?

I have a date text field with an image using the input-group-addon class as below for using with a date picker: [http://getbootstrap.com/components/#input-groups]

<div class="form-group">
    <div class="input-group date datepicker" data-date-format="dd/mm/yyyy">
        <input type="text" name="visitdate" class="form-control" data-validation="date" data-validation-format="dd/mm/yyyy" value="" />
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
</div>

Unfortunately when I run the validation the error message seems to break the formatting from this:

![image](https://cloud.githubusercontent.com/assets/5912234/2719872/f8ef2198-c567-11e3-834c-aa41ab538224.png)

to this:

![image 1](https://cloud.githubusercontent.com/assets/5912234/2719847/ab6ecb80-c567-11e3-90e5-08851a99e587.png)

All of the other field types seem to be fine, just when including an image or text in the form of an input-group-addon class.

Thank you.

**Comment by victorjonsson** [comment]
In this case you should use `data-validation-error-msg-container` to point out another element where possible error dialog should be displayed. (http://www.formvalidator.net/#configuration_position)

```html
<div class="input-group">
      <input data-validation="required"
             data-validation-error-msg-container="#error-container"
             class="form-control">
      <span class="input-group-addon" id="basic-addon2">@example.com</span>
    </div>
    <div id="error-container"></div>
```

**Comment by sekhar-88** [comment]
place that error class for that specific input field in a div isolated. the error will go there.
