### ISSUE TITLE
Give a specific display error message for an input error

### ISSUE THREAD

**Issue by khoude24** [victorjonsson/jQuery-Form-Validator#133]
I use some plugin and sometime the display error message appear in wrong place. It could be nice if we can have an option like data-error-display-position ="ID_OF_A_ELEMENT" . I know you have the  errorMessagePosition  option but its not what i need  Thx ! :)  

Here the probleme: 

![b8beee54d1ae7a77750bd41d37f2a97099d0e81d](https://cloud.githubusercontent.com/assets/4171752/2841943/d1274cc8-d06e-11e3-8c1b-4222573e32df.jpg)

**Comment by victorjonsson** [comment]
This was fixed in issue #222
