### ISSUE TITLE
Disabling Validation on Specific Submit

### ISSUE THREAD

**Issue by Shyamalangan** [victorjonsson/jQuery-Form-Validator#134]
I have a form where I have two buttons (SAVE, CANCEL). But buttons are submitting. But the SAVE button should validate (This is working), the CANCEL button should submit without validating.

**Comment by jcarraou** [comment]
Disabling validation on specific submit would be a very helpfull functionality.

For example, designing a step by step wizard form using two submit buttons:
- one to validate step, saving data with validation and going to next step
- one to go back in the wizard, only saving data to find them back when going forward

**Comment by victorjonsson** [comment]
Having a specific class, on a submit button, that disables the validation feels too implicit. I believe that this is an edge case that should require custom code. Making the solution a part of the plugin feels unnecessary, the code example above is a good enough solution.

**Comment by jcarraou** [comment]
Thank you for the answer. My idea is to have something like the formnovalidate HTML attribute:
http://www.w3schools.com/tags/att_input_formnovalidate.asp
