### ISSUE TITLE
Optional validation

### ISSUE THREAD

**Issue by worfoual** [victorjonsson/jQuery-Form-Validator#153]
It's not really an issue but I try to do somethink and I just can't achieve it.
I have an input field (text): company_name not required
I have an input field company_adres (text) and I want this one to be required only if company_name is not empty

Is it possible to get this working? I know it works with a checkbox: data-validation-if-checked
But I can't get it working with a input field type text.
Sorry for my poor english.
My regards,
Francois

**Comment by victorjonsson** [comment]
This feature has now moved into the module "logic". Using the old attribute data-validation-if-checked is considered deprecated and will trigger a console warning.

**Validate input if a checkbox is checked**
```html
<p>
   E-mail:
   <input data-validation="required email" data-validation-depends-on="agreement" />
</p>
<p>
  Lorem te ipsum
  <input type="checkbox" name="agreement" value="1" />
</p>
...
<script>
   $.validate({
     modules: 'logic'
   });
```

**Require US state if user comes from USA**
```html
<p>
   Home country:
   <select name="country">
       ...
       <option value="USA">USA</option>
       <option value="Uganda">Uganda</option>
       ....
   </select>
</p>
<p>
   State:
   <input 
      name="state"
      data-validation="federatestate required"
      data-validation-depends-on="country"
      data-validation-depends-on-value="USA"
    />
</p>
...
<script>
$.validate({
   modules: 'logic, location'
});
</script>
```
