### ISSUE TITLE
Password Confirmation not working

### ISSUE THREAD

**Issue by Ankurl** [victorjonsson/jQuery-Form-Validator#156]
Hello there,i am using form validator for my form but the password confirmation is not working.

<p>
  Password (at least 8 characters)
  <input name="pass_confirmation" data-validation="length" data-validation-length="min8">

  Confirm password
  <input name="pass" data-validation="confirmation">
</p>

i have correctly loaded the scripts.Any help?

**Comment by patrickbjohnson** [comment]
Currently running into the same issue of the password confirmation not working. But noticed I'm getting an error:

```Using undefined validator "validate_confirmation"```

Here's a screenshot: http://cl.pbj.me/image/2u3B2r0p1B13

I'm developing locally at the moment and using the CDN script. Although I recieved the same error by including the plugin with a bower script. 

Currently developing on Chrome Version 39.0.2171.99 (64-bit) on Mac.

**Comment by patrickbjohnson** [comment]
Disregard comment above. I totally forgot to add the security module. All is working fine now.

**Comment by ikOrbis** [comment]
Why can we not download the minified js and use it as a local version? When I do that, I am getting this error: "validate_confirmation". Is there a way I could use this locally?
