### ISSUE TITLE
Initialize via existing DOM element(s) instead of selector string

### ISSUE THREAD

**Issue by swemaniac** [victorjonsson/jQuery-Form-Validator#172]
Hi,

First off thanks, great plug. I'd like to see the ability to initialize the validator on a given DOM element(s) instead of having to provide a string selector.

E.g. $('.my-form').validate(options);

**Comment by swemaniac** [comment]
Any idea when 2.2.0 will be released?

**Comment by riccardobevilacqua** [comment]
Looking forward to 2.2.0
