### ISSUE TITLE
Adding multiple validators to a single field

### ISSUE THREAD

**Issue by renet** [victorjonsson/jQuery-Form-Validator#195]
Hi there, I'd like to add multiple validators to a single field, for example:

    <input type="text" name="val" data-validation="email,length" data-validation-length="6-200">

to validate for a valid email that's not longer than 200 characters. Many other combinations would be of interest for me, as well. Especially for custom validators I added.

I think the error message should be displayed according to the priority/order of the validators. `data-validation="email,length"` should first display the email error message, if an invalid email is given AND an input shorter than the allowed length is entered. For `data-validation="length,email"` it should be the other way around.

**Comment by victorjonsson** [comment]
I'm unable to reproduce this. The error dialogs are displayed in accordance to the priority/order of the declared validation rules.
