### ISSUE TITLE
Suggestion: Custom Error Handler + Disable Error Messages

### ISSUE THREAD

**Issue by ethanpil** [victorjonsson/jQuery-Form-Validator#202]
I know about the `onError` event as well as the `errorMessagePosition` settings.

I want to use my own notification window system to display errors. So I would like to see a feature where I can setup something like this:

````
$.validate({
   form : '#myform',
   disableErrorNotice: true,
    onError : function(errors) {
       $(errors).each(function(el){
                //Do something with each el
        })
    },
});

````

With `disableErrorNotice` i completely disable the internal error notification system, alternativly we can add `errorMessagePosition:  'disable'` and reuse existing config option...

With `onError` I am passed `errors` which is an array of element objects that failed validation and i can then call my notiification system...

**Comment by victorjonsson** [comment]
This is possible to achieve with version 2.2 (not yet released) with some custom code, using `$('form').isValid(conf, lang, displayErrors)`

```js

var errors = [] 
    conf = {
       onElementValidate : function(valid, $el, $form, errorMess) {
          if( !valid ) {
             errors.push({el: $el, error: errorMess});
          }
       }
   },
   lang = {
       ...
   }

$('#myform').on('submit', function() {
   // reset error arr
   errors = [];
   if( !$(this).isValid(conf, lang, false) ) {
        // Use errors array with your own message system
        ...
        return false;
   }
});

```
