### ISSUE TITLE
Issues with Jquery Date Picker

### ISSUE THREAD

**Issue by ghosternguyen** [victorjonsson/jQuery-Form-Validator#203]
I have a datebirth validator
`<input type="text" name="birthdate" id="birthdate" value="" size="25" data-validation="birthdate" data-validation-format="dd/mm/yyyy" />`

And my Jquery Date Picker should pick a date in "dd/mm/yyyy" format

Your validator seem doesn't work when I pick a date from my Date Picker but it works when I type by my keyboard, any suggestion?

**Comment by victorjonsson** [comment]
I'm not able to reproduce this. http://jsbin.com/jacepazofo/1/edit
