### ISSUE TITLE
Validate date without zero ie 1/1/2015

### ISSUE THREAD

**Issue by yehudahkay** [victorjonsson/jQuery-Form-Validator#205]
Great plugin, however if a date is entered without the zero (1-1-2015 instead of 01-01-2015) it doesn't validate. Is this a bug?

**Comment by victorjonsson** [comment]
It's a feature :) Could add an attribute that determines whether or not leading zeros should be required

````
<input data-validation="birthdate" data-validation-require-leading-zero="false" />
```

**Comment by stevevance** [comment]
I've run into this problem. My form has two date fields and I'm copying data from Excel that has no leading zero. I like @victorjonsson's idea for preferring one method versus another.
