### ISSUE TITLE
Validate "year" date type

### ISSUE THREAD

**Issue by chidalgom** [victorjonsson/jQuery-Form-Validator#206]
Hi victorjonsson, thanks for this amazing plugin...

I need, if possible, validate a date but only for years (4 digits), already try the data-validation-format="yyyy" but does not work (only works if the format is like dd/mm/yyy), and of course, a number validatiion may work but have a custom error messages for this. need to know if this is possible.

Thanks a lot.

**Comment by victorjonsson** [comment]
I'm surprised it doesn't work with `yyyy`. I will look into it. 

I would solve it using `range[min;max]`

```html
<strong>Year of birth:</strong<br />
<input type="number"
       data-validation="number" 
       data-validation-allowing="range[1900;2015]" 
       data-validation-error-msg="This is not a valid year of birth" />
```
