### ISSUE TITLE
Is it possible to have the error message change depending on the validation?

### ISSUE THREAD

**Issue by kae24** [victorjonsson/jQuery-Form-Validator#207]
Is it possible to use more than one validator on one input?
If not could a custom module change the error message in the validation function?

**Comment by victorjonsson** [comment]
Yes, you can put multiple validation rules on a single input. You can also customize the error dialog on inputs

```html
<input name="user" 
       data-validation="length alphanumeric" 
       data-validation-length="min5" 
       data-validation-error-msg="Invalid user name" />
```

http://formvalidator.net/#localization
