### ISSUE TITLE
UK domain validate fails

### ISSUE THREAD

**Issue by wgstjf** [victorjonsson/jQuery-Form-Validator#209]
Hi,

Great script!  I have a problem though, the email validation fails on the new(ish) domain suffix '.uk'.  I have take a look at the code and it seems to be an issue arising from the fact that there are also domain suffixes like '.uk.com'.  How can I get it to successfully validate an email address like this: test@test.uk?

Cheers,

Will

**Comment by wgstjf** [comment]
Hi there....any chance of a quick fix to sort this out as the project has to go live at the end of the week?

Cheers,

Will

**Comment by olaj** [comment]
I also have user complaining about this. I guess what is basically needed nowadays is to allow "whatever" as a domain.

**Comment by wgstjf** [comment]
I agree...too many new ones coming out to be able to cover all of them easily...either that or allow a variable to extend the allowable suffixes with custom ones.  Either way really need an answer here Victor...even if it is a quick fix...Cheers

**Comment by victorjonsson** [comment]
Yes, I agree as well.... So what would be good enough validation of a domain name, that it contains atleast one punctuation mark and that it begins with letters an ends with atleast two letters?

**Comment by wgstjf** [comment]
That would be perfect! :-)

**Comment by Magnanimity** [comment]
Hi, I am having an issue on email validation with domains that start with numbers. These domains are valid, such as 9gag.com, 44dudley.co.za. Could you update the email validation to also allow the email domain to start with numbers? Alternatively, is there a way to add an "exception" when $.validate() is called?
