### ISSUE TITLE
Relocating specific error message.

### ISSUE THREAD

**Issue by muyaszed** [victorjonsson/jQuery-Form-Validator#212]
Hi I am trying to relocate an input error message inside another div. I would like to relocate on this error message. So I am trying to use jquery for this.

Below is my html

```php
<div class="medium-2 column end">
<input type="text" id="captcha" name="captcha" data-validation="spamcheck" data-validation-captcha="<?=( $_SESSION['captcha'][0] + $_SESSION['captcha'][1] )?>">
</div>
<div id="captcha-error" class="medium-12 column"></div>
```

when validate  and have error I would like to move the span inside #capture-error div.
Below is my jquery

```javascript
$('#captcha').on('validation', function(evt, isValid) {
    if( !isValid ) {
      $('#captcha').next().clone().appendTo("#captcha-error");
      $('#captcha').next().hide();
    }
  });
```
Somehow it does not work, probably someone could help. or maybe is there any other solution for me to relocate only this error message. Thanks in advance

**Comment by victorjonsson** [comment]
There's a thought-out way to relocate the error message and I'm sorry that it's not mentioned in the documentation.

When the error message gets displayed the validator will look for an element that has id `[INPUT-NAME]_err_msg`. So in your case when the input is named `captcha`you should set the id to `captcha_err_msg`. Here's a working example http://jsbin.com/xuzexapeki/1/edit
