### ISSUE TITLE
Server side validation - the post variable name is same as the input name

### ISSUE THREAD

**Issue by appyape** [victorjonsson/jQuery-Form-Validator#214]
I have an issue with the server side validation. When the validation ajax request is sent it takes the name of the input field and sends as the post data e.g. if input field was named "email" then the post data is Array('email' => 'adfasdfsd'); This works fine if it was one off requirement. But if I need a generic server side validation code to do similar checks for different input fields, then it isn't possible with this config. If the name of the post data key is hardcoded to, say, "userinput", then I could use the same code to validate many different forms or better if it was configurable.

Can you please advise if it possible or not?

**Comment by appyape** [comment]
also if I was validating an email address on the server side and checking if it was already taken, it would work fine for adding a new record but the server side code would need more parameters, say, an ID to ignore the duplicate check on the current record.

**Comment by victorjonsson** [comment]
In the unreleased version of this plugin (the master-branch here on github) you can add parameters to the request.

```js
var params = {...}; // will be sent along with the server request as POST-parameters
$('#the-input').attr('data-validation-req-params', params);
```

The variable name of the input can not be configured but it seems reasonable that you should be able to. I will implement it so that you define it with `data-validation-param-name="..."`
