### ISSUE TITLE
Checkbox group not removing error message

### ISSUE THREAD

**Issue by hergy80** [victorjonsson/jQuery-Form-Validator#222]
When using the validation "checkbox_group" on the initial item of a group, it will not remove the error message when an item in the group without the markup is selected.  For example, 3 checkboxes with the same name are in a form with the validation tag on the first one.  A submit happened and they are invalidated.  When you check box 2 or 3, the error tag is never removed.  If you select box 1, it removes the error message.  But if you check box 2 or 3 and click submit, it will validate ok.

Sample:
```
<label><input name="position[]" type="checkbox" data-validation="checkbox_group" data-validation-qty="min1" value="Sales">Sales/Counter</label>
<label><input name="position[]" type="checkbox" value="Production">Production</label>
<label><input name="position[]" type="checkbox" value="Management">Management</label>

```

**Comment by victorjonsson** [comment]
Found a bug affecting this. Will try to have it fixed soon.
