### ISSUE TITLE
Optional date validation

### ISSUE THREAD

**Issue by mbigatti** [victorjonsson/jQuery-Form-Validator#223]
Hi. I've a form with a date field that is optional. In other words, user can fill in the field, and in this case it should be validated, or leave it empty. In this case the field should be considered valid. I've browsed the docs and the source code and it appears to me that this is not possible right now. Maybe it would require a custom validator?
thx

**Comment by mbigatti** [comment]
For now I'm doing this

    $.formUtils.addValidator({
        name : 'date',
        validatorFunction : function(date, $el, conf) {
        	var optional = $el.valAttr('optional');
        	if (date.length == 0 && optional) {
        		return true;
        	}
            var dateFormat = $el.valAttr('format') || conf.dateFormat || 'yyyy-mm-dd';
            return $.formUtils.parseDate(date, dateFormat) !== false;
        },
        errorMessage : '',
        errorMessageKey: 'badDate'
    });

**Comment by victorjonsson** [comment]
http://formvalidator.net/#default-validators_optional

**Comment by mbigatti** [comment]
thank you and sorry I didn't see that, my bad
