### ISSUE TITLE
Help block position for checkbox_group

### ISSUE THREAD

**Issue by jaredatch** [victorjonsson/jQuery-Form-Validator#224]
Having an issue with the help block positioning when using checkbox_group.

Here is what happens http://cl.ly/image/0b0N2x3R2L0w

![Layout Issue](https://s3.amazonaws.com/f.cl.ly/items/1A0b3e0E3J1U0t1t2a13/Screen%20Shot%202015-03-22%20at%204.54.25%20PM.png)

I think my layout is fairly common. Essentially it is:
```
<li>
<input><label>Some Label</label>
</li>
```
Even with other layouts, I can't see how the current positioning would work well. So what ends up happening is the help block just gets oddly appended to the first element.

What would be better would be positioning it after the last element. I tried just applying checkbox_group to the last element to see if that would achieve this but it didn't work. Another option would be if the help block got prepended to the input.

Any ideas?

**Comment by victorjonsson** [comment]
It's now possible to handle these rather special situations using `data-validation-error-msg-container`. Example:

```html
<div>
   <div id="error-container"></div>
   <strong>Lorem te ipsum</strong>
   <ul>
      <li>A <input type="checkbox" name="var[]" value="A"
                     data-validation="checkbox_group"
                     data-validation-qty="1-3"
                     data-validation-error-msg-container="#error-container"></li>
      <li>B <input type="checkbox" name="var[]" value="B"></li>
      <li>C <input type="checkbox" name="var[]" value="C"></li>
      <li>D <input type="checkbox" name="var[]" value="D"></li>
      <li>E <input type="checkbox" name="var[]" value="E"></li>
      <li>F <input type="checkbox" name="var[]" value="F"></li>
   </ul>
</div>
```
