### ISSUE TITLE
Apply content validation without being required.

### ISSUE THREAD

**Issue by jaredatch** [victorjonsson/jQuery-Form-Validator#225]
Here is the idea behind this.

What if you have a form that has an email text field (or URL etc) that is optional.

Since it is optional, if it isn't filled out obviously nothing should happen and should not trigger any validation.

If the field does get filled out (not empty on submit) then we run the validation against what was inputted.

This would allow users to have optional date, email, url, etc and help ensure if they are filled out, they are filled out correctly, BUT allow them to be optional.

For example many times on contact forms you will have an email and phone number fields, with them both optional. If a user doesn't enter an email address that is fine, however if they decide to provide one we want to make sure it is valid.

**Comment by victorjonsson** [comment]
That feature is already implemented http://formvalidator.net/#default-validators_optional. Let me know if you have any more great ideas!

**Comment by jaredatch** [comment]
Whoops, don't know how I missed that. Thanks!
