### ISSUE TITLE
Element error message position

### ISSUE THREAD

**Issue by mantoze** [victorjonsson/jQuery-Form-Validator#226]
Now element error message goes to:
<span class="help-block form-error">...</span>

How to send element error message to my own div (example: div class="my-error").
This div have all elements of the form.

**Comment by victorjonsson** [comment]
http://formvalidator.net/#configuration_position

**Comment by mantoze** [comment]
Thanks
now i understand... own error container id must be "INPUT-ELEMENT_err_msg"
but in documentation i can't find this...

**Comment by Hacktivista** [comment]
I could not find this on the docs neither, please add :)

**Comment by victorjonsson** [comment]
The solution based on "INPUT-ELEMENT_err_msg" feels rather implicit, it should be considered deprecated and will probably be removed in the future.

There are two different ways to specify where an error message should appear. Either you use the attribute `data-validation-error-msg-container` on the input-element containing the css-selector of the element where the error message should be placed. The other option is to use the configuration parameter `errorMessagePosition` to tell the plugin where all error messages should be placed.

All this is described on http://formvalidator.net/#configuration_position

**Comment by Hacktivista** [comment]
It's simpler than assigning data-validation-error-msg-container for each element. The other option would be to allow writing a function on "errorMessagePosition" as "function(element)". This because it's always better to write where the message will be just once than on every single input.

**Comment by victorjonsson** [comment]
Letting the `errorMessagePosition` accept a callback function would be great feature! I'll add that as a feature request.

**Comment by thwuersch** [comment]
The same callback solution should be implemented for help text positioning.

**Comment by victorjonsson** [comment]
This will change a bit. This is how the implementation will look

```js
config.errorMessagePosition = function(args) {
   switch(args.context) {
      case 'inline':
         // Return an element that should contain the error message.
         // This callback will only be called in case validateOnBlur is set to true (which is default) 
         // Return false to prevent the error dialog from being displayed
         break;
      case 'form':
         //  Return an element that should contain all error messages
         //  Return false to prevent the error dialogs from being displayed
         break;
  }
};
```

Content of `args`

```js
{
   context: 'inline', // Either 'inline' or 'form'
   errorMessages: [] // Array with error messages that will be applied. This can also be an empty array if the validator is about to remove an error message
   $input: ...; // Only present if context is inline, referring to the input that triggered the failed validation
   $form: ...; // Only present if context is form, referring to the validated form 
}
```
