### ISSUE TITLE
Add support for .nyc domains in email

### ISSUE THREAD

**Issue by EmanNo1** [victorjonsson/jQuery-Form-Validator#228]
Hello, I am having an issue with email addresses that have .nyc as the top level domain. 

Thanks,
Eirk

**Comment by victorjonsson** [comment]
What version of the plugin are you using? The version 2.1.47 distributed via cdn?

**Comment by victorjonsson** [comment]
This is however fixed in the latest version of the plugin available here on github (not yet released)

**Comment by EmanNo1** [comment]
Thanks Erik Martinson 


     On Wednesday, April 1, 2015 12:30 AM, Victor Jonsson <notifications@github.com> wrote:
   

 Closed #228.—
