### ISSUE TITLE
Password strength display in Rails project

### ISSUE THREAD

**Issue by chathu020** [victorjonsson/jQuery-Form-Validator#230]
I have used jQuery-Form-Validator for my rails project. I have included password strength display function in script. But it is not showing? what are the required js files. I have loaded all the files in Form-Validator folder.

**Comment by victorjonsson** [comment]
Do you get access to the default validators?

**Comment by chathu020** [comment]
yes I can access default validators and can check password strength also. The problem is it is not showing the password strength like "week, strong,etc". But when I load script from http://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.1.47/jquery.form-validator.min.js it works fine.

**Comment by chathu020** [comment]
hi!
Is there a way to bind password confirmation input with password input
within javascript other than referring with name attribute. ex:pass,
pass_confirmation

**Comment by victorjonsson** [comment]
This is supported in the latest version available here on github (not yet released).

```html
<p>
  E-mail
  <input name="user-email" data-validation="email">

  Repeat e-mail
  <input name="repeat" data-validation="confirmation" data-validation-confirm="user-email">
</p>
```

I will look into the first issue, the strength-indicator not showing.

**Comment by chathu020** [comment]
ok thank you. For password confirmation I have added custom script
validation.
The other problem was in example forms when the input is entered it
highlights and shows icon at right side to indicate right or wrong. That
also not working in my application. Is that required any css file to
include.

**Comment by victorjonsson** [comment]
Yes that requires some css. It would look something like:

```css
input.valid {
    background: lightgreen;
    color: #002f00;
}

input.error {
    background: pink;
    color: #480000;
}
```

**Comment by chathu020** [comment]
I thought that comes with default features of plugin.
