### ISSUE TITLE
Password confirm validation empty value

### ISSUE THREAD

**Issue by igidas** [victorjonsson/jQuery-Form-Validator#231]
form-validator/security.dev.js
line 52 should be:
`return value && value === conf;`

Because now, password confirm input is valid if it is empty and compared input is empty.

**Comment by victorjonsson** [comment]
This can be discussed :) In my opinion you should set the password-input to be required. Example:

```html
<p>
   Password: 
   <input name="pass" type="password" data-validation="required" />
</p>
<p>
   Repeat password:
   <input name="pass_confirmation" type="password" data-validation="confirmation" />
</p>
```
