### ISSUE TITLE
intercept space and arrow keys

### ISSUE THREAD

**Issue by ocote42** [victorjonsson/jQuery-Form-Validator#233]
Dear all

I'm not sure it's an issue but I encounter a problem on a fomular. When I use <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.1.47/jquery.form-validator.js"></script>
 in my code, on the formular I can no longer enter a space nor use arrow keys to move in the field.

Does anyone have a suggestion ? Do you need further information ?

If this kind of question shouldn't appear here please can you tell me a more convenient place ?

**Comment by victorjonsson** [comment]
Stackoverflow.com
