### ISSUE TITLE
Cyrillic chars not supported

### ISSUE THREAD

**Issue by ArthurShlain** [victorjonsson/jQuery-Form-Validator#235]
Cyrillic symbols not supported in alphanumeric validation.

**Comment by victorjonsson** [comment]
Simply because the alphanumeric characters does not include cyrillic characters.

**Comment by victorjonsson** [comment]
Closing this issue. The topic is being discussed in #249

**Comment by victorjonsson** [comment]
This is now supported using the validator `letternumeric` in the security module

http://formvalidator.net/#security-validators_letternumeric
