### ISSUE TITLE
Confilct with IntlTelInput plugin

### ISSUE THREAD

**Issue by ArthurShlain** [victorjonsson/jQuery-Form-Validator#236]
IntlTelInput plugin make a wrapper for input with class "intl-tel-input", then jQuery Form Validator append "has-error" to him instead of 'form-group'.

Possible fix:

after 
if($parent.hasClass("input-group")) $parent = $parent.parent();

add:
if($parent.parent().hasClass("form-group")) $parent = $parent.parent();

It is better to do a check through "closest" method

**Comment by victorjonsson** [comment]
Like you say, using ´$.closest´ would probably be best.

**Comment by victorjonsson** [comment]
The way that the plugin finds the parent container is now changed. It will maybe help with your problem.
