### ISSUE TITLE
Select box server side validation not working

### ISSUE THREAD

**Issue by kallevf** [victorjonsson/jQuery-Form-Validator#237]
Server side validation with select boxes only works for first select. When changeing value the validation will not be triggered again.

Here is a JSFiddle showing this: http://jsfiddle.net/v2bby9nk/
1) Select value "test", blur field - server side validation will fail.
2) select value "secret", blur field - server side validation will not run again and form can not be submitted.

**Comment by victorjonsson** [comment]
This might already been fixed in the upcoming version. I'll look into it.
