### ISSUE TITLE
Is it possible to validate on keyup?

### ISSUE THREAD

**Issue by somme** [victorjonsson/jQuery-Form-Validator#239]
I need to validate fields on keyup instead of on blur.

**Comment by lokhi** [comment]
I think you can do it check the Validate On Event part in the Readme. 
Try with ```data-validation-event="keyup"``` on the input and ```validateOnEvent : true,``` in the configuration

**Comment by victorjonsson** [comment]
That is correct...

**Comment by akashk92** [comment]
Where should I write logic on keyup validation??

**Comment by victorjonsson** [comment]
You should declare your own validator http://www.formvalidator.net/#custom-validators

```html
<form>
...
<input data-validation="custom_validator">
...
</form>
<script>
$.formUtils.addValidator({
  name : 'custom_validator',
  ...
});
$.validate({
   validateOnEvent: 'keyup'
});
</script>

**Comment by akashk92** [comment]
I have done this already, but formUtils executes only when I type there first,
If I type elsewhere then I type on customValidator then it doesn't work.

**Comment by victorjonsson** [comment]
I'm not following you... I need to see you code

**Comment by akashk92** [comment]
I just found your solution works,
but as focusOut Event.
Means Whenever I loose focus of input then it triggers formUtils validator.
But not when keyup.

**Comment by akashk92** [comment]
Hey I figured out solution,
I had to use keydown event. It solved the problem @victorjonsson
