### ISSUE TITLE
How to add validation to a dropdown menu?

### ISSUE THREAD

**Issue by Goardo-43** [victorjonsson/jQuery-Form-Validator#241]
Hi all,

I'm very new to using this validation but do have it working successfully on all my inputs. I'm using a very basic method to call in a standard message 'Please complete the highlighted fields' if a field/input is not completed.

However, adding the same code to the <select> tag within my dropdown menu isn't working at all. Is there a specific way to add this?

Any help for this newb appareciated!

Code I'm using below.... is working perfectly on inputs.

<label for="CustomField_2590_1">Where you heard about us? *</label>
<select name="CustomField_2590_1" id="CustomField_2590_1" data-validation="required" data-validation-error-msg="Please complete the highlighted fields" /><option value="0">-- Please Select --</option><option value="6177">From a friend / contact</option><option value="6153">Google search</option><option value="6445">Yahoo search</option></select>

Many thanks

G

**Comment by victorjonsson** [comment]
```html
<select data-validation="required">
  <option value="">- - Make a choice - -</option>
  <option value="A">First choice</option>
  <option value="B">Second choice</option>
</select>
```
