### ISSUE TITLE
Change error message location based on input?

### ISSUE THREAD

**Issue by ManOrMonster** [victorjonsson/jQuery-Form-Validator#242]
I'm using <a href="http://www.appelsiini.net/projects/jeditable">Jeditable</a> for one of my inputs, so naturally it does not stay an input by the time the form is submitted. To get around this, I have a hidden input that is updated based on the content.

The problem is that the validator does not append the error message to the hidden input, placing it at the bottom of the form instead. Is there any way to specify an element to attach just that one error message to, while letting the other messages do the default behavior?

I'm currently using 2.2.beta.69 (so that I can validate radio inputs).

**Comment by victorjonsson** [comment]
In the latest version available only here on github lets you solve this using `data-validation-error-msg-container` See issue #224

**Comment by ManOrMonster** [comment]
Perfect! This is exactly what I was looking for. Thanks!
