### ISSUE TITLE
Is there a way of checking if a single input/textarea element is valid?

### ISSUE THREAD

**Issue by TomCaserta** [victorjonsson/jQuery-Form-Validator#245]
Something like $("#myElement").isValidated() or similar?

Reason I want to do this is to save drafts of a form when they leave an input and would like a way of validating a single element. I couldnt immediately see anything in the documentation for this.

**Comment by victorjonsson** [comment]
It's possible but it's not really a part of the API and can therefor be subject to change without a proper backwards compatible solution provided. It wouldn't be possible to use the event `validation` ?

```js
$('#the-form *[data-validation]').on('validation', function(evt, isValid) {
  if( isValid ) {
     console.log('Input '+this.name+' is valid.');
  } else {
     console.log('Input '+this.name+' is NOT valid.'); 
  }
});
```

http://formvalidator.net/#configuration_callbacks
