### ISSUE TITLE
validate on button click not submit

### ISSUE THREAD

**Issue by Hasan-git** [victorjonsson/jQuery-Form-Validator#246]
How to run validation on button type click not submit type click

**Comment by bally86** [comment]
Just read the documentation:)
http://formvalidator.net/#configuration_submit

**Comment by Brotakuu** [comment]
validateOnBlur : false

doesnt work as stated in the documentation

**Comment by victorjonsson** [comment]
Please explain the expected behavior from setting `validateOnBlur` to false.
