### ISSUE TITLE
Language packages

### ISSUE THREAD

**Issue by victorjonsson** [victorjonsson/jQuery-Form-Validator#248]
Distribute translated error dialogs together with the plugin.

```js
$.validate({
   lang : 'it'
});
```

Languages are referenced in accordance to ISO 639-1

**Comment by ReneMuetti** [comment]
Hello
I have charged the current code-master down. I then tried to involve the localization - without any success. The method 'onModulesLoaded' is not called ....
Version: 2.2.19

```html
        <script type="text/javascript" src="../elemente/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="../elemente/jquery.form-validator.min.js"></script
```
....
```javascript
        $.validate({
            'form'     : '#nachricht',
            'lang'     : 'de',
            'modules'  : 'security',

            'onModulesLoaded': function(){
                alert('ok');
            },

            'onError'  : function(){
                alert('Fail');
            },
            'onSuccess': function(){
                alert('Ok');
            }
        });
```
All reports shall be made in English ...
The alert for 'onModulesLoaded' never fires ...

I do something wrong?

**Comment by victorjonsson** [comment]
Im not getting any errors when trying out your initiation code. It works as expected and alerts "ok" when the modules has loaded. What does your js-console say?

**Comment by victorjonsson** [comment]
Okey, now I see. When you use the downloaded source code you must put the module files in the same directory as jquery-form-validator.min.js. Normally you would put the entire directory `form-validator` in your application. Like:

```html
<script type="text/javascript" src="../elemente/form-validator/jquery.form-validator.min.js"></script>
```

**Comment by ReneMuetti** [comment]
Okay - this was the right note :)
if "modules" a module to be loaded, which does not exist fails to initialize completely. Since no log output is done, I can not understand the law. I now have the security.js filed with the directory and lo and behold - it works :)

Possibly an error in the log should be written if such a thing occurs.

**Comment by victorjonsson** [comment]
I agree. 

But you could actually have detected it using the console. If you had looked at the network traffic you had seen that the request to security.js resulted in 404-response from the server.

**Comment by ReneMuetti** [comment]
I agree with that. But I still think this is an entry in the Console more visible. if possible, that would certainly be a good thing
