### ISSUE TITLE
European language chars

### ISSUE THREAD

**Issue by bally86** [victorjonsson/jQuery-Form-Validator#249]
The alphanumeric validation does not allow chars like é, ë, etc.
These are common used chars in multiple european languages.

**Comment by victorjonsson** [comment]
Yes, they are common in many languages but they're not **alphanumeric** http://en.wikipedia.org/wiki/Alphanumeric

**Comment by bally86** [comment]
Allright, maybe a new feature then that will allow these kind of chars?

**Comment by victorjonsson** [comment]
It could be possible to have a validation named something like "letternumeric" that allows any type of letter and numbers.

**Comment by bally86** [comment]
That would be great

**Comment by nickpierpoint** [comment]
An option for matching Unicode characters using regular expressions is described here  http://stackoverflow.com/questions/6381752/validating-users-utf-8-name-in-javascript.

It involves using the XRegExp plugin: http://xregexp.com/plugins/
