### ISSUE TITLE
Turn off error per-element or per-form messages without custom form validation

### ISSUE THREAD

**Issue by nickpierpoint** [victorjonsson/jQuery-Form-Validator#252]
Hi. I'd like the option of not displaying any error messages after validation and just have the visual notification that comes from adding an error CSS class.

For example:

    errorElementMessage : ""

or

    errorMessagePosition : "none"

My workaround this is to override the error message style:

    <style>
        .help-block.form-error {
            display:none;
        }
    </style>

My use case for this is a grid of INPUT fields that can only accept numbers and adding a per-element error message isn't appropriate.

I know I can workaround this by adding custom `isValid()` but I'd prefer to use the automatic validation handling.

Thanks very much.

**Comment by victorjonsson** [comment]
You could also send the error dialogs to en element that is hidden, if you don't want your form markup to become cluttered with elements containing the error dialogs.

I find both of these approaches as good enough solutions. I probably won't implement errorMessagePosition : "none" any time soon.
