### ISSUE TITLE
Validation-Question....

### ISSUE THREAD

**Issue by ReneMuetti** [victorjonsson/jQuery-Form-Validator#255]
```html
<input name="plz" type="text" id="plz" data-validation="length" data-validation-length="5" />
```
I have the box as defined in the Code. Unfortunately, it is so that the field is not validated, the validator correctly. When I write in 1 character, it is precisely in order, as if I only write 4 in. However, it must be (in Germany) exactly 5 numbers.
I do not know how complicated it is to allow the data validation option. These are then carefully checked in the following order:
Example:
```html
<input name="plz" type="text" id="plz" data-validation="length number" data-validation-length="5" />
```
This would only check the length and then only numbers. so you could all make it very dynamic.

**Comment by victorjonsson** [comment]
hm.. it's possible to validate an exact number characters by using `[min]-[max]`

```
data-validation-length="5-5"
```

**Comment by victorjonsson** [comment]
I change the implementation so that if you declare only a number it will be interpreted as 5-5 by the validator automatically.

**Comment by ReneMuetti** [comment]
Oh - then I understood the "wrong" ...
but thank you very much, they adjust it accordingly :)

**Comment by ReneMuetti** [comment]
identical with https://github.com/victorjonsson/jQuery-Form-Validator/issues/195
