### ISSUE TITLE
Changing event for the element Validation

### ISSUE THREAD

**Issue by puchito85** [victorjonsson/jQuery-Form-Validator#257]
Hello,

I was trying to integrate the plugin with the bootstrap-select (which only wraps a visual container on the browser). The problem I was having to integrate it with this plugin is that this plugin only triggers a 'blur' event over the <select> element. 

This means that the validation plugin isn't able to grasp the change because it's expecting a 'blur' event and the error will still be there (if it was displayed).

Is it possible to change the event to which the validation will run off to? I've seen there is a 'data-validation-event' attribute, but I think it's only used for some internal naming or something like that.

Thank you, and great plugin by the way! 

PD: new lines seem to dissapear after the editor for some reason. Sorry about that.

**Comment by victorjonsson** [comment]
You should be able to use `data-validation-event`.

```html
<select data-validation="required" data-validation-event="change">
  <option value="">- - - Pick your choice - - -</option>
  ...
</select>

<script>
$.validate({
  validateOnEvent : true
})
</script>
```

**Comment by puchito85** [comment]
You're awesome! I was missing the "validateOnEvent" attribute.

Thank you!

**Comment by MajorMashin** [comment]
@victorjonsson is there a way i can use `data-validation-event="change"` globally?

**Comment by victorjonsson** [comment]
I'm afraid not, you will have to write some code for that.

```js
$('[data-validation]').attr('data-validation-event', 'change');
```
