### ISSUE TITLE
Two Sets of Radio Inputs Validation

### ISSUE THREAD

**Issue by heyepic** [victorjonsson/jQuery-Form-Validator#258]
First off, love the script.

I have two sets of radio buttons, both have data-validation=required on them. If I don't choose either, submission stops and points it out. However, if I ignore the first set, and only fill out a radio from the second set - the form submits.

**Comment by victorjonsson** [comment]
I would need to see the code inorder to help you out.

**Comment by heyepic** [comment]
Sure - I took this off our development server so it's very crude.

http://redlinedigitalmedia.com/test/

You can fill out first name, last name, bogus email, then click submit.
Then, you can click Paypal and click Submit and it'll still process.

On Tue, May 19, 2015 at 2:24 PM, Victor Jonsson <notifications@github.com>
wrote:

> I would need to see the code inorder to help you out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorjonsson/jQuery-Form-Validator/issues/258#issuecomment-103641598>
> .
>



-- 
Matt Bohlman Website Developer, Graphic Designer
Portfolio <http://www.mattbohlman.com> | LinkedIn
<http://www.linkedin.com/in/mattbohlman>

**Comment by victorjonsson** [comment]
Hm.. I have not had time to investigate this thoroughly but I believe that this might have something to do with the html5-module. Could you try changing the from value `true` to `required` when you set an input field as required using javascript

```js
$(...).attr('required', true);

// instead write
$(...).attr('required', 'required');
```

**Comment by heyepic** [comment]
Tried a bunch of different stuff and still no. I'm not sure that html5 flag
is doing any good for me so I removed it as I see no change in my scenario.

If you come up with anything, let me know. Thanks for looking into it
nonetheless.

On Wed, May 20, 2015 at 8:25 AM, Victor Jonsson <notifications@github.com>
wrote:

> Hm.. I have not had time to investigate this thoroughly but I believe that
> this might have something to do with the html5-module. Could you try
> changing the from value true to required when you set an input field as
> required using javascript
>
> $(...).attr('required', true);
> // instead write
> $(...).attr('required', 'required');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorjonsson/jQuery-Form-Validator/issues/258#issuecomment-103887733>
> .
>



-- 
Matt Bohlman Website Developer, Graphic Designer
Portfolio <http://www.mattbohlman.com> | LinkedIn
<http://www.linkedin.com/in/mattbohlman>

**Comment by victorjonsson** [comment]
Yes, I will try to have this issue solved before next release.

**Comment by victorjonsson** [comment]
The use case for the html5-module is when you're using validators that is natively supported. Then you declare only the native validation attributes and use the html5-module only to ensure cross-browser/cross-version support. If you mix native declarations and data-validation attributes you will end up with different styling on the error dialogs on different inputs, which would be a negative user experience.

**Comment by heyepic** [comment]
Understood. Thanks for dedicating some time this, Victor.

On Thu, May 21, 2015 at 4:07 AM, Victor Jonsson <notifications@github.com>
wrote:

> The use case for the html5-module is when you're using validators that is
> natively supported. Then you declare only the native validation attributes
> and use the html5-module only to ensure cross-browser/cross-version
> support. If you mix native declarations and data-validation attributes you
> will end up with different styling on the error dialogs on different
> inputs, which would be a negative user experience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorjonsson/jQuery-Form-Validator/issues/258#issuecomment-104188127>
> .
>



-- 
Matt Bohlman Website Developer, Graphic Designer
Portfolio <http://www.mattbohlman.com> | LinkedIn
<http://www.linkedin.com/in/mattbohlman>

**Comment by victorjonsson** [comment]
I have now investigated this further. It seems that when you click on one of the radio buttons for the payment an input named `amount` gets the attribute `data-validation` set to `true`. Since it does not exist any validator named `validate_true` an error will be thrown and the form gets posted.
