### ISSUE TITLE
Problems on validating a textarea

### ISSUE THREAD

**Issue by cborchmann** [victorjonsson/jQuery-Form-Validator#259]
Hallo,

i try to validate a simple form using a textarea:

```html
 <form accept-charset="UTF-8" role="form" id="addcomment" action="<?php echo "$referenz";?>" method="post">
     <div class="form-group">
      <textarea  id="editor" name="com_text" class="form-control" style="width: 100%; height: 400px" data-validation="required"></textarea>
  </div>
      <button type="submit" class="btn btn-primary btn-block" name="submit">Submit</button>
      /form>
<script src="<?php echo $site_path?>/js/form-validator/jquery.form-validator.min.js"></script>
<script>
  $.validate({     });
</script>
```
After first click on submit button the erroe message "You have not answered all required fields" shows up... Just fine :-)
When i click the button once again the form sends the empty textbox...

Any hints to me? using the Form-Validator on my loginform works fine, no probmens there...

Thanks

Christian

**Comment by victorjonsson** [comment]
This kind of question is better suited to be on stackoverflow or any other QA-forum.

The markup of your form looks fine. The content of the textarea should be available using `$_POST['com_text']`. Maybe doing somehting like this will help you out.

```php

if( !empty($_POST) ) {
   var_dump($_POST);
   die;
}

```
