### ISSUE TITLE
Make validation optional from a checkbox group with validation

### ISSUE THREAD

**Issue by ratherbesurfing** [victorjonsson/jQuery-Form-Validator#260]
Is it possible to use the below technique (of making a field validate only if a checkbox is checked) when said checkbox is in a group with validation also applied?

http://formvalidator.net/#default-validators_optional

As the checkbox for the above needs to have a unique name, I'm not sure how get both the checkbox group and optional validation working together.

Many thanks for any guidance.

**Comment by greyhard** [comment]
Yes, you miss type radio if-cheked validation :) please fix it )

**Comment by wmalgadey** [comment]
+1

**Comment by wunc** [comment]
+1 for this feature.

What would be a better overall feature (that would also solve this issue) would be optional validation based on another field's current value.

Maybe the implementation could look something like this (just my proposal):

```html
<input name="mygroup" type="radio" value="one">
<input name="mygroup" type="radio" value="two">
<input name="mygroup" type="radio" value="three">
<input name="..." data-validation="email" data-validation-if-value="mygroup=two">
```
