### ISSUE TITLE
Form submit not working in IE8

### ISSUE THREAD

**Issue by ArthurShlain** [victorjonsson/jQuery-Form-Validator#261]
```
$.validate({
  form : '.cpLoginForm',
  language: myLanguage,
  modules : 'security'
});
```

```
<form name="loginform" action="/wp-login.php" method="post" class="cpLoginForm" autocomplete="off">
	<div class="form-group has-feedback">
		<label class="sr-only" for="log">Email</label>
		<input data-validation="email" class="form-control" id="cp_email" name="log" type="text" placeholder="E-mail" autocomplete="off">
		<span class="cpInputStatus glyphicon glyphicon-remove form-control-error"></span>
		<span class="cpInputStatus glyphicon glyphicon-ok form-control-success"></span>
	</div>

	<div class="form-group has-feedback">
		<div class="cpPasswordInput">
			<label class="sr-only" for="cp_password">Password</label>
			<input data-validation="length" data-validation-length="min8"
				   class="form-control" id="cp_password" name="pwd" type="password"
				   placeholder="Password">
			<span class="cpInputStatus glyphicon glyphicon-remove form-control-error"></span>
			<span class="cpInputStatus glyphicon glyphicon-ok form-control-success"></span>
		</div>
	</div>

	<input type="hidden" name="redirect_to" value="<?php echo $_SERVER['REQUEST_URI']; ?>">
	<input type="submit" id="sendCpForm" name="wp-submit" class="bigredbutton" value="Log in">
</form>
```

**Comment by ArthurShlain** [comment]
Hm... It is not IE8... After i update this plugin on my site from version 2.2.beta.60 to latest form submit not working :cry:

**Comment by victorjonsson** [comment]
Good to know. When you say latest version, exactly which version is it? The last stable version is 2.2.1

**Comment by ArthurShlain** [comment]
Yes, 2.2.1

**Comment by victorjonsson** [comment]
I'm not able to reproduce this. Everything works as expected http://jsbin.com/sobebizije/1/edit

What does your js-console say?

**Comment by victorjonsson** [comment]
Okey, I found it!

**Comment by ArthurShlain** [comment]
http://jsbin.com/qaduzezoja/2/edit?html,console,output

alert('test') not shown

**Comment by victorjonsson** [comment]
Well, it has nothing to do with jquery-form-validator it seems. I'm getting tons of net::ERR_CONNECTION_TIMED_OUT in the js-console.

**Comment by victorjonsson** [comment]
Doesn't your js-console say anything at all?

**Comment by ArthurShlain** [comment]
Sorry, site owners blocks other ip-addreses... OK... I check my scripts and write if found something

**Comment by ArthurShlain** [comment]
http://jsbin.com/gawevedahe/1/ - version 2.2.34 (not working)

http://jsbin.com/letemiziyu/1/ - version 2.2.beta.60 (working in chrome, not working in IE8)

Form has hidden fields (visibility change by radio buttons - login/register). But in 2.2.34 alert not shown.

**Comment by victorjonsson** [comment]
http://jsbin.com/sugomavuha/1/ Is working. You know that hidden fields also gets validated?  The only problem I'm getting in IE8 is that nothing happens when I click on "НЕТ".

*What did or did not work in the beta version is no longer relevant*

**Comment by ArthurShlain** [comment]
How correct way to solve it? In version 2.2.beta.60 hidden fields not validated?

**Comment by ArthurShlain** [comment]
Ok, I solve it by adding attribute "disabled" for hidden fields. In IE8 works.
