### ISSUE TITLE
how validate an input that depends on the value of the other input

### ISSUE THREAD

**Issue by xhava** [victorjonsson/jQuery-Form-Validator#262]
Hi. someone could help me;
how can i validate an input that depends on the value of another input.
for example i have 3 inputs 

i just want to validate if input number two is required, but only if the value of the input one is 1
if the value of input one is equal 2, i want to validate the input number two and tree to required

**Comment by zingoy-akashbijwe** [comment]
Hey,
I having same issue, I want to validate particular input fields on button click, Not to validate whole form.
code snippet:

$(".btn").on("click",function(){
   $(".abc").validate();  //validate a particualar input field.
});
