### ISSUE TITLE
server side validation

### ISSUE THREAD

**Issue by achezzoh** [victorjonsson/jQuery-Form-Validator#263]
when server side validation is combined with another validation, it fails with the error message "connection failed with status ok".

**Comment by victorjonsson** [comment]
I'm not able to reproduce this. Could you please provide me with a code example.

**Comment by achezzoh** [comment]
Sorry about that, there was a small bug with my code and i already fixed it. My other issue is that i have a form am trying to submit using ajax, having bound a function to its submit event, issue is that the form submits even after it has failed the validation. is it possible to get the validity state of the form maybe by just calling some function, or checking for some class added to the form if validation fails, so that i can stop the submission if needed?
i cannot use onSuccess/onError handler because i have initialised the validation in a general way for 3 forms, using some custom property i added to all of them. i hope i have not missed something this time...

**Comment by victorjonsson** [comment]
Use `$.isValid()` 

```js
var config = {},
     lang = {},
     displayErrors = false;

if( $('#my-form').isValid(config, lang, displayErrors) ) {
   // it's valid....
}

```

http://formvalidator.net/#configuration_submit

**Comment by achezzoh** [comment]
that solved it, and thanks for this plugin, i truly like it!

**Comment by Jim266** [comment]
Hi there,
Thanks so much for the great work.

I have the same issue that achezzoh had.  Any idea how achezzoh fixed.  I have another page which work perfectly though.  The following is how I coded:
`<form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post" enctype="multipart/form-data" class="sign-in"  form="frmPwdRcry" id="frmPwdRcry">
            		<div class="form-group">
                    	<label>User Name</label>
                        <input name="usrname" id="usrname" type="text" placeholder="Enter you user name" class="form-control" data-validation="alphanumeric" data-validation-error-msg="Your user name is mandatory" autofocus>
                	</div>
                	<div class="form-group">
                    	<label class="control-label" for="emailaddr">Email</label>
           				<input class="form-control" name="emailaddr" id="emailaddr" placeholder="Enter 	registered email address here" data-validation="email server" data-validation-url="validate-emailaddr3.php" /> 
                	</div>
                	<div class="form-actions">
                        <button name="send" id="send" type="submit" class="btn btn-sm btn-primary btn-block "><i class=" icon-lock "></i>&nbsp;Reset Password</button>               
                    	<div class="clearfix"></div>
                	</div>
            	</form>`
`<script>
	$.validate({
    	modules : 'security'
  	});

	$.validate({
  		form : '#frmPwdRcry'
	});
</script>`
`<?php
include_once ('includes/admin_common_hdr.php');
include_once ('includes/user.php');
$response = array(
  'valid' => false,
  'message' => 'Post argument "email" is missing.'
);
if( isset($_POST['emailaddr']) ) {
  $used = chkEmailAddrInUse($_POST['emailaddr']);
  if ($used) {
 	$response = array('valid' => true);	
  } else {
  	$response = array('valid' => false, 'message' => 'This email does not exist.');
  }
}
echo json_encode($response);
?>`
