### ISSUE TITLE
localization: Issue with accented characters

### ISSUE THREAD

**Issue by anpegar** [victorjonsson/jQuery-Form-Validator#264]
Hi !!

I've changed the language to Spanish and the accented characters doesn't appears correctly (check out image). What are doing wrong?

Thanks in advance.

`<!doctype html>`
`           <html class="no-js" lang="">`
`           <head>`
`                <meta charset="utf-8">`
`                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">`
`                <title>CRM</title>`
`                <meta name="description" content="">`
`                <meta name="viewport" content="width=device-width, initial-scale=1">`
`</head>`
`           <script type="text/javascript" src="/js/jquery/plugins/form-validator/form-validator.min.js"></script>`
`           <script type="text/javascript" src="/js/jquery/plugins/form-validator/lang/es.dev.js"></script> `

`<script>`
` $.validate({`
`  form : ".form-profile",`
`  lang : "es"`
`});`
`</script>`
`</html>`

![captura](https://cloud.githubusercontent.com/assets/8124520/8334668/67728114-1a99-11e5-8fe6-a84d2c4009c4.PNG)

**Comment by victorjonsson** [comment]
I'm unable to reproduce this. I think that you might have saved the language-file converted from utf-8 to another charset. Could you provide me with some more information, what's your technology stack? Is there any differences between browsers?

**Comment by anpegar** [comment]
Hi Victor, 
thank you very much for your reply and you're right about saving the file in other charset. The issue was the following, I use sublime text editor and this editor has UTF-8 charte by default and my oracle data base doesn't support UTF-8.

Sorry for the issue.

**Comment by victorjonsson** [comment]
No problem, thanks for reporting what you thought was an issue with the plugin itself.
