### ISSUE TITLE
Email Validation Not working in IE8

### ISSUE THREAD

**Issue by m0rg4nb4t35** [victorjonsson/jQuery-Form-Validator#265]
In IE8 all email addresses are marked as bad,  this is because in the domain validation you are using this line 
!(/[^a-zA-Z0-9]/.test(val.substr(- 2)))

The W3C page states that negative values in the substr function will not work in IE8.  I came up with a simple solution around that that you may want to implement in the next release.

!(/[^a-zA-Z0-9]/.test(val.substr(val.length - 2)))

still gets the same thing, but will work in all browsers.

**Comment by victorjonsson** [comment]
What version of the plugin are you using? I'm not able to find this.
