### ISSUE TITLE
Error message not correctly placed with form-group attribute

### ISSUE THREAD

**Issue by slolo2000** [victorjonsson/jQuery-Form-Validator#266]
Hello,

It seems to have a strange behavior with the current version 2.2.35 if you use form-group attribute in your HTML. The parent is not correctly selected when using form-group class (as specified on bootstrap web site)

Please have a look to this example: https://jsfiddle.net/7mb2jrxq/ for the source code
And this link http://i59.tinypic.com/2u58ayo.jpg in order to see the diffrence on the source code

For information, it works well with a previous version 2.2.beta.60

I hope you will be able to fix it.

Thanks in advance and have a nice day.

**Comment by victorjonsson** [comment]
You're not using the suggested form markup http://getbootstrap.com/css/#forms

- The input element should not be wrapped in a div.
- There's no point in having a grid-class on the label element (`col-sm-4`)

Here you can take a look at a working example https://jsfiddle.net/s135gk6x/

Let me know if you run into any other issues.
/ vic

**Comment by slolo2000** [comment]
Hello,

Thanks a lot for your for your response but I am not agree with you.
In my case, I want to use "Horizontal form" from bootstrap and the syntax I have used is the correct syntax as described on bootstrap documentation (see http://getbootstrap.com/css/#forms-horizontal)

I really think that there is a small bug in your plug-in and it does not support this specific syntax of Bootstrap "Horizontal form"

Can you confirm this behavior?

**Comment by victorjonsson** [comment]
That is correct. The plugin currently does not support horizontal forms. Will have it fixed in next release.
