### ISSUE TITLE
callbacks not work

### ISSUE THREAD

**Issue by edades** [victorjonsson/jQuery-Form-Validator#271]
Hi, i have this code and when i press the button, the alert no show and in my console no there errors.
When the input lose the focus this yes show the success/error style/message.

Thanks

```javascript
$("#btnSaveRegister").on('click',function(){
  $.validate({
    onSuccess : function() {
      alert('Valid!');
      return false; // prevent ordinary form submission
    },
    onError : function() {
      alert('no valid!');
    },
  });
});
```

**Comment by victorjonsson** [comment]
The function `$.validate` is a setup function that will by itself bind necessary event listeners. You should therefor call it as soon as possible, not when the submit button of your form gets clicked.

```js
  $.validate({
    form : '#my-form'
    onSuccess : function() {
      alert('Valid!');
      return false; // prevent ordinary form submission
    },
    onError : function() {
      alert('no valid!');
    },
  });
```

http://formvalidator.net/#configuration_setup
