### ISSUE TITLE
html5 type="number" and floats

### ISSUE THREAD

**Issue by FireSBurnsmuP** [victorjonsson/jQuery-Form-Validator#277]
It seems that just a vanilla HTML5 input won't validate as a float without adding `data-validation-allowing="float"`.

That is:
```html
<input type="number" min="0.0" max="6.0" step="0.5">
```
Will show invalid if, say, '4.5' were entered, but validate fine if '4' is entered, even though native validation would handle this just fine.

However:
```html
<input type="number" min="0.0" max="6.0" step="0.5" data-validation-allowing="float">
```
works as expected.

This is an easy workaround, but I think that this could be easily auto-detected by checking if the `step` is a float.

**Comment by victorjonsson** [comment]
Hm... what version of the plugin are you using? I'm not able to reproduce this bug when using the latest version from the master branch.

**Comment by FireSBurnsmuP** [comment]
I'm using 2.2.34; let me try and get it to happen with the most recent version. You have fixed #276 so it's time to upgrade, anyway.

I suppose including which browser I have the issue with would be helpful, too. I've got browser testing to do anyway, so I'll do that, too.

**Comment by FireSBurnsmuP** [comment]
Using 2.2.40, floats are now working without the extra `data-validation-allowing` attribute in Chrome 43, FF 39, IE11, and Opera 30.

I have no means of testing anything else, but suffice it to say, I think you fixed this somewhere along the way.

**Comment by victorjonsson** [comment]
The fact is that there is an issue related to this. But it has nothing to do with floating point numbers. When you have declared an input having the type number it will become impossible to get the value of the input unless its a valid number. What this means is that it will not be possible to have an input of type number that is optional, the input will always be required
