### ISSUE TITLE
Prevent scroll

### ISSUE THREAD

**Issue by gbgkogkas** [victorjonsson/jQuery-Form-Validator#278]
I am building an app where I use some modals with forms.
When there is an error inside the form the validator will scroll over the modal
Is there any way to control/prevent scroll to error?

**Comment by victorjonsson** [comment]
Have you tried srcollToTopOnError: false

**Comment by Aratm** [comment]
I tried it right now and didn't work.
We are using version 2.1.56.
Is this feature supported on this version?

**Comment by victorjonsson** [comment]
What does the js-console say?

**Comment by gbgkogkas** [comment]
$.validate({
        borderColorOnError  : false,
        validateOnBlur      : false,
        showHelpOnFocus     : false,
        addSuggestions      : false,
        srcollToTopOnError  : false,
        language            : APP_LANG.VALIDATOR,
        modules             : 'customValidators, security',
        form                : '#'+formId,

Those are my selected attributes.
It does not console anything it is as if, the attribute is not recognized/ignored.

**Comment by victorjonsson** [comment]
`srcollToTopOnError` should be **scr**ollToTopOnError

**Comment by gbgkogkas** [comment]
Thank you for your help!

**Comment by alexandremaeda** [comment]
I set:
