### ISSUE TITLE
error in $.isValid() function documentation.

### ISSUE THREAD

**Issue by tom4dev** [victorjonsson/jQuery-Form-Validator#279]
According to the official documentation (http://formvalidator.net/#configuration_submit:Validate) , we can use the method ```$.fn.isValid``` in that way:
```$.isValid(config, lang, displayErrors)``` 

But to work without any issues, we need to call the function in that way:
```$.isValid(lang, config, displayErrors);```

Indeed we need to reverse the order ("```lang``` parameter" before "```config``` parameter") and it works like a charm !
Just saying ! ;)

**Comment by victorjonsson** [comment]
Ops, now fixed :)
