### ISSUE TITLE
Wouldn't it be nice if we can trigger the validation programmatically (or is it already possible)?

### ISSUE THREAD

**Issue by ahmedtabrez** [victorjonsson/jQuery-Form-Validator#280]
Shouldn't it be possible to trigger validation of an input field not at onBlur but in a different event like for example in an ajax callback function that updates the input field itself? (or is this functionality already there?)

<b>Update:</b> If I understood rightly, <code>$.isValid()</code> validates the whole form, not a single input. I am talking about a single input validation.

**Comment by victorjonsson** [comment]
Something like this https://github.com/victorjonsson/jQuery-Form-Validator#validate-on-event ?

**Comment by ahmedtabrez** [comment]
@victorjonsson, but that limits us to the DOM events. Isn't it ? ... What If we wanna call it from within our code? Let's say we have three inter-related input fields and the third among them is based on the first two fields and is filled not by a user but by our javascript. How do we trigger validation of first and second input on gaining focus at the third field? 
.
Let me know if I wasn't clear enough ...

**Comment by victorjonsson** [comment]
In that case you have two different options to choose between. 

#### 1) Trigger the blur event manually

```js
$('#some-button').on('click', function() {
    var $inputs = $('.input-group input');
    $.ajax({
       url : '/some/path',
       success : function(data) {
            // add input values programatically 
            $inputs.trigger('blur'); // validates the inputs
       }
    })
});
```
Pretty straight forward solution but it requires that you use `validateOnBlur` (which is enabled by default).

#### 2) Use the internal function $.formUtils.validateInput

```js

var $myForm = $('#the-form'), 
      myLanguage = { ... }, // Can also be set to false if not wanting to override any error dialogs
      myConfig = { 
          language : myLanguage,
          ...
      };

// Setup the validation
$.validate(myConfig);

// Add some values to inputs and then run validation on the same
$('.some-button').on('someEvent', function() {
   var $myInput = $('#the-input');
   $myInput.val( Math.random() );
   
   $.formUtils.validateInput($myInput, myLanguage, myConfig, $myForm, 'blur');
})
```
This would be something of a hack. It's not mean to be part of the "public API" of this plugin. The use of this function might partly, or completely, change (it might even be removed) without notice.

**Comment by ahmedtabrez** [comment]
Yes of course, the solutions u have mentioned are hacky .... But I doubt if its the ideal one. Kindly take this thread as a <b>Feature Request.</b> This feature can be added and made more elegant.
Thankyou ... 😊

**Comment by victorjonsson** [comment]
It's now possible to call `.validate` on any element.

```js
$('#the-input').validate(function(valid, elem) {
   console.log('Element '+elem.name+' is '+( valid ? 'valid' : 'invlid'));
});

// Override configuration set by calling $.validate()
$('#the-input').validate(function(valid, elem) {
   console.log('Element '+elem.name+' is '+( valid ? 'valid' : 'invlid'));
}, {errorMessagePosition: $('#error-wrapper')});

```
