### ISSUE TITLE
HTML5 not working

### ISSUE THREAD

**Issue by Hacktivista** [victorjonsson/jQuery-Form-Validator#281]
HTML5 validation is not working for me :/ Not even on the examples

**Comment by victorjonsson** [comment]
What version of the plugin are you using? What browser have you tested? How does your code look like?

**Comment by MueR** [comment]
Same for me. 

JS: 
    $.validate({
        form: '#form-register',
        modules: 'html5, security',
        onModulesLoaded : function() {
            console.log('All modules loaded!');
        },
        onElementValidate : function(valid, $el, $form, errorMess) {
            console.log('Input ' +$el.attr('name')+ ' is ' + ( valid ? 'VALID':'NOT VALID') );
        }
    });

HTML:
    <div class="form-group">
        <label for="register-email" class="control-label">Email address</label>
        <input type="email" class="form-control" name="email" id="register-email" placeholder="Email address" value="{{ values.email|default() }}" required="required">
    </div>
    <div class="form-group">
        <label for="register-password" class="control-label">Password</label>
        <input type="password" class="form-control" name="password" id="register-password" placeholder="Choose a password" value="" required autocomplete="off" data-validation="length" data-validation-length="min{{ constant('\Master::PASSWORD_MIN_LENGTH') }}">
    </div>
    <div class="form-group">
        <label for="register-password-confirm" class="control-label">Confirm password</label>
        <input type="password" class="form-control" name="password-confirm" id="register-password-confirm" placeholder="Confirm your password" value="" data-validation="confirmation" data-validation-confirm="password">
    </div>

The onModulesLoaded is not firing, html5 required is not working (not with just `required` shorthand or `required="required"` fully written), the only thing I see in the JS console is:
`Uncaught Error: Using undefined validator "validate_confirmation"`
