### ISSUE TITLE
Apostrophe in email address validation

### ISSUE THREAD

**Issue by jhnk** [victorjonsson/jQuery-Form-Validator#283]
I notice that standard characters A-Z, numbers 0-9, dashes (-), underscore (_) or periods (.) are allowed but it seems apostrophe is not. It is not that common but i notice more people are using apostrophe in their email address

It will be nice if apostrophe is a valid character in email address

**Comment by victorjonsson** [comment]
Yes, the email adress validator needs some fixing https://en.wikipedia.org/wiki/Email_address#Local_part
