### ISSUE TITLE
Currency Format [New feature: data sanitation]

### ISSUE THREAD

**Issue by jhnk** [victorjonsson/jQuery-Form-Validator#284]
I know we can add float and decimal but is it possible to get currency format in a number validation e.g. number displaying as 5,500.25

**Comment by victorjonsson** [comment]
Would this be good enough?

```html
<input data-validation="custom" data-validation-regexp="([0-9]+),([0-9]+)\.([0-9]+)" />
```

**Comment by jhnk** [comment]
Hi Victor,

Thank you for your response. 

Not exactly. I am trying to look for a way to update the number automatically. e.g when i type 5000, it will be displayed as 5,000

**Comment by victorjonsson** [comment]
Ah. That has not so much to do with validation but I thought about having a module that could contain general utility functions that might be useful when dealing with form data.

**Comment by victorjonsson** [comment]
By using the module `sanitize` you will be able to declare sanitation functions that will be triggered when input/textarea looses focus. You declare them using the attribute `data-sanitize`. The implemented rules are:

- trim
- trimLeft
- trimRight
- upper (convert all letters to upper case)
- lower (convert all letters to lower case)
- capitalize (convert the first letter in all words to upper case)
- insertRight (declare a text that should be inserted at the end of the value, attribute `data-sanitize-insert-right`)
- insertLeft (declare a text that should be inserted at the beginning of the value, attribute `data-sanitize-insert-left`)
- escape (convert < > & ' " to html entities)
- numberFormat (use the attribute `data-number-format` in accordance to the definitions described on http://numeraljs.com/. Note that this rule requires that numeral.js is included in the page)

**Comment by victorjonsson** [comment]
Example:

```html
<form>
   <p> 
     How much do you want to donate?<br>
     <input type="text" name="how much" />
</form>

```
