### ISSUE TITLE
Error with form-horizontal?

### ISSUE THREAD

**Issue by rogovdm** [victorjonsson/jQuery-Form-Validator#287]
```javascript
if ( !$parent.hasClass('form-group') && !$parent.closest('form').hasClass('form-horizontal') ) {
          var $formGroup = $parent.closest('.form-group');
          if ($formGroup.length) {
            return $formGroup.eq(0);
          }
        }
```

I believe it should be 

```
$parent.closest('form').hasClass('form-horizontal') 
```
not
```javascript
!$parent.closest('form').hasClass('form-horizontal') 
```

**Comment by rogovdm** [comment]
I can't find a way to work with a mark up like this

<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>

**Comment by victorjonsson** [comment]
Hm.. I'm not able to reproduce this bug, the error dialogs seems to place them self just fine http://jsbin.com/xotorulupi/edit?html,output.

What version of the plugin are you using? What version of bootstrap are you using?

**Comment by victorjonsson** [comment]
Give me a holla if this still seems to be an issue.
