### ISSUE TITLE
OnSuccess

### ISSUE THREAD

**Issue by jhnk** [victorjonsson/jQuery-Form-Validator#292]
How do i display a message on the form informing people that it will take a minute to process the form? Currently i have it as an alert (would like to avoid that) but how do i display it as a text or message while the form is processing/loading?

onSuccess : function() {
	alert('this may take a minute, we appreciate your patience');
	return true;
},

**Comment by victorjonsson** [comment]
```js

var showModal = function(text) {...},
  removeModal = function() {...};

$.validate({
   onError : removeModal
});

// Show modal when submit button is pressed
$('[type="submit"]').on('click', showModal);
