### ISSUE TITLE
How to disable validation for element that have property display none

### ISSUE THREAD

**Issue by AnjumBanaras** [victorjonsson/jQuery-Form-Validator#293]
I have few input elements on page. I have to hide 2 input fields on user selection and i don't want those 2 to get validated if they are hidden.
I am not able to submit form as it look like the hidden fields are get validated and hence not allowing form to submit.

Thanks..

**Comment by CY5** [comment]
i alos had the same problem make those field hidden and add these line 
$.formUtils.defaultConfig['ignore']=["input[type='text']:hidden"];

**Comment by victorjonsson** [comment]
That attribute can only contain an array with input names
