### ISSUE TITLE
Validation in IE Browser

### ISSUE THREAD

**Issue by jhnk** [victorjonsson/jQuery-Form-Validator#294]
Is there any reason why in IE browser(ie 8 and 9) text field is not validating? all other browser are executing the validation perfectly. But when i set IE browser document mode to quirk mode, validation work but it makes my form looks really bad. Is there any way around this?

<div class="notificationbox" id="v3"></div>

<input class="form-control" name="addressline" id="addressline" type="text" placeholder="Address" data-validation="required" data-validation-error-msg="Address field is empty" data-validation-error-msg-container="#v3">

**Comment by victorjonsson** [comment]
I'm not able to reproduce this error. What version of jQuery are you using?
