### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by chrisz3ch** [victorjonsson/jQuery-Form-Validator#295]
cannot install via bower, when extracting archive.tar.gz gives error: 
"EINVALID Failed to read C:\Users\CHRIS~1\AppData\Local\Temp\chris\bower\jQuery-Form-Validator-6696-DyHaJe\bower.json"

Installig other bower packages works fine.

tx chris

**Comment by victorjonsson** [comment]
I'm not able to reproduce this. How does your bower.json look like?

**Comment by chrisz3ch** [comment]
most basic bower setup, see attached bower.json and .bowerrec

I could bower install jQuery-Form-Validator from my local drive after manually downloading and unpacking jQuery-Form-Validator-2.2.43.tar.gz, but only after stripping bower.json to it’s bare minimum (see attached as bower.json.mod).

With the original I got this error:

 



 

With modified bower.json;

(jquery install only to show that its works just fine)

 



 

Aside from that Form Validator is great, even got it to work with jtable ;-)

 

Tx chris

**Comment by victorjonsson** [comment]
The error messages are missing :(

**Comment by chrisz3ch** [comment]
Error with locally unzipped files and original bower.json:

 

U:\data\develop>bower install F:\downloads\misc\jQuery-Form-Validator-2.2.43 --log-level=debug

bower copy          F:\downloads\misc\jQuery-Form-Validator-2.2.43

bower copy          F:\downloads\misc\jQuery-Form-Validator-2.2.43

bower EINVALID      Failed to read F:\downloads\misc\jQuery-Form-Validator-2.2.43\bower.json

 

Additional error details:

The name contains upper case letters

 

 

Error via source from git:

 

U:\data\develop>bower install jQuery-Form-Validator --log-level=debug

bower not-cached    git://github.com/victorjonsson/jQuery-Form-Validator.git#*

bower resolve       git://github.com/victorjonsson/jQuery-Form-Validator.git#*

bower download      https://github.com/victorjonsson/jQuery-Form-Validator/archive/2.2.43.tar.gz

bower extract       jQuery-Form-Validator#* archive.tar.gz

bower EINVALID      Failed to read C:\Users\CHRIST~1\AppData\Local\Temp\G7-christoph\bower\jQuery-Form-Validator-9520-gM3mSz\bower.json

 

Additional error details:

The name contains upper case letters

 

U:\data\develop>

**Comment by victorjonsson** [comment]
Okey, this will be fixed in next release.

**Comment by chrisz3ch** [comment]
Tx!
