### ISSUE TITLE
Using with select2 jquery plugin

### ISSUE THREAD

**Issue by etcho** [victorjonsson/jQuery-Form-Validator#297]
There's some way to validade select2 components? It hides the original select, and its events doesn't get called (blue, focus, change). Through the submit buttom I got it to work changing some css classes, but the instant validation with events still not working.

**Comment by Igloczek** [comment]
```javascript
var youSelect = $('select');
yourSelect.change(function() {
    yourSelect.validate({ validateHiddenInputs: true });
});
```
Should work good enough :)
