### ISSUE TITLE
Validation do not fire if input is auto-filled by browser or other things

### ISSUE THREAD

**Issue by Saurabh11Sharma** [victorjonsson/jQuery-Form-Validator#298]
Validation do not fire if an element is auto filled by browser.
for example: for login username and password is saved at user end and browser auto fill them on load.
This do not fire any event and validate form. Also causing 'toggleDisabled' button in disabled state.

**Comment by victorjonsson** [comment]
Having a solution that fixes this problem might be tricky...
http://avernet.blogspot.in/2010/11/autocomplete-and-javascript-change.html

**Comment by victorjonsson** [comment]
I have decided to not invest time in this, for the following reasons:

- The inputs that gets autofilled will still become validate when you hit submit
- In the special case mentioned above, when using "toggleDisabled", it still works, the only thing is that the user must put focus on the inputs to enable the submit. If you dislike this behaviour you can always set `autocomplete="off"` on the form element.
