### ISSUE TITLE
file validation with ajax() submit file

### ISSUE THREAD

**Issue by utainn** [victorjonsson/jQuery-Form-Validator#302]
I try to use ajax() to submit file to php with file validator but it shown error message "undefine index" code like below, what'm I wrong? thank you

```js
var submitForm = function($form) {
   var formURL = $form.attr("action");
   var postData = $form.serialize();
   $.ajax({
		url : formURL,
		type: "POST",
		data : postData,
		enctype: 'multipart/form-data',
              	processData: false,  // tell jQuery not to process the data
              	contentType: false,   // tell jQuery not to set contentType
		success:function(data, textStatus, jqXHR) {
				alert(data);     
		}
   });
};

$.validate({
	form : '#uploadform',
	modules : 'security,file',
	onSuccess : submitForm			
});
```

**Comment by victorjonsson** [comment]
Where does it say "undefined index"? In the alert dialog?

**Comment by utainn** [comment]
yes , there are undefined index for al field name in form submit

**Comment by victorjonsson** [comment]
I don't see how this can have anything to do with this jquery plugin. If it's an alert dialog displaying a message from back-end then there's somehting wrong with you php code.

**Comment by utainn** [comment]
In PHP, I just return file name as below , code is only single line

echo $_FILES["fileToUpload"]["name"];

**Comment by victorjonsson** [comment]
Which is apparently wrong.... try var_dump($_POST); var_dump($_FILES); to see what your form is sending

**Comment by utainn** [comment]
after submitting, first the alert message shown "array(0){  } " then click "OK" redirect to php page (upload.php) and show message on this page as below

[upload.php]
array(1) { ["fileToUpload"]=> array(5) { ["name"]=> string(6) "PV.png" ["type"]=> string(9) "image/png" ["tmp_name"]=> string(22) "C:\xampp\tmp\phpFA.tmp" ["error"]=> int(0) ["size"]=> int(127215) } }
