### ISSUE TITLE
Wrong email validation

### ISSUE THREAD

**Issue by Saurabh11Sharma** [victorjonsson/jQuery-Form-Validator#304]
Email validation not working correct. 
For example: If we write 'dfbdjhb,@jhbj.com' (please note it has [,] comma)
In this case it validates the email.
![password](https://cloud.githubusercontent.com/assets/12280522/9994828/b6fe83a6-609c-11e5-8eb3-0115f0959ef2.PNG)

**Comment by Saurabh11Sharma** [comment]
** UPDATE **

* Same issue with ['] single quote, [;] semi colon, [:] Colon, [~] tilde, [!]  exclamation mark, [#] hash and so on...

**Comment by jrhalchak** [comment]
Those are all valid for the local portion of an email according to specs.  True email validation is tough, I'm surprised the plugin accounted for that.

Reference: https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses

**Comment by victorjonsson** [comment]
https://github.com/victorjonsson/jQuery-Form-Validator/issues/283
