### ISSUE TITLE
Need property to validate Input only on blur or loose focus

### ISSUE THREAD

**Issue by Saurabh11Sharma** [victorjonsson/jQuery-Form-Validator#314]
I am validating a from, and using toggleDisabled feature.
Form validate the input every time I press a key even on tab to get the new field.
On tab both previous and new fields get validated.

Is this possible to validate the field only on blur, mean any property to attach.

**Comment by victorjonsson** [comment]
Well why would you want that? What's the behaviour that you find faulty?

The default setup will validate the inputs in several steps. First the user types in an input. The user then switches to another input. This triggers the blur event on the input currently focused, which then becomes validated. The input will from now on also become validated on keyup. This is to give the user immediate feedback when correcting the value of the input. The user last of all clicks the submit button and all inputs will now become validated once more.

**Comment by jclay** [comment]
@victorjonsson I think he's talking about how the behavior when tabbing through the form changes when you use `toggleDisabled`

I've attached an example gif. Notice when I tab to the next input, the empty box is validated before I type.
![t0t2i](https://cloud.githubusercontent.com/assets/1047986/10700858/90977e24-798e-11e5-8a57-d814af1f9aff.gif)

I was able to fix it by removing this line, in effect not attaching to the keyup event.
https://github.com/victorjonsson/jQuery-Form-Validator/blob/master/form-validator/toggleDisabled.dev.js#L40

Is there any reason why this functionality exists that I'm overlooking?

**Comment by victorjonsson** [comment]
I believe that it would be considered better UX to enable the submit button immediately while typing, not requiring the user to move on to the next field before showing if the input is valid. This is especially important when having the configuration option `showErrorDialogs` set to false. 

However, this is still an erroneous behaviour that needs to be fixed. It should trigger the validation on keyup, like it currently does, as long as it's not a tab.
