### ISSUE TITLE
Updating to v. 2.2.8 or 2.2.82 from v. 2.2.1 seems to make data-validation-optional not work for input type number

### ISSUE THREAD

**Issue by rayHInstart** [victorjonsson/jQuery-Form-Validator#315]
After upgrading, the following mark-up behaves incorrectly:
```
 <input type="number" id="timeout" data-validation="number" 
  data-validation-optional="true"/> 
```
The field seems to always be validated even though data-validation-optional is marked as false. In v. 2.2.1 this worked fine and only validated when a value was entered.
Changing the input type to text seems to fix this, but it's not semantic so that's a hack.

**Comment by victorjonsson** [comment]
This has somehting to do with inputs of type number. I will look into it, meanwhile a quick fix is to set the type to `text`

**Comment by rayHInstart** [comment]
OK thanks :)
