### ISSUE TITLE
Validation after sanitation makes number invalid

### ISSUE THREAD

**Issue by JorindeReijnierse** [victorjonsson/jQuery-Form-Validator#323]
I'm using input validation for number with sanitation number formatting and numeral.js
```
data-validation="number"
data-sanitize="numberFormat"
data-sanitize-number-format="0,0"
```
For example when I put in 80000 it validates as valid and formats as 80,000.
but when I focus on the input again and defocus it again the number is invalid. If I put the the numeral language setting on nl-nl (thousandseparator: .  & decimalseperator: ,) it also formats from 80.000 to 80 when refocussing.
it there a way to fix this?  do I have to deformat the value some way when focusing again?

**Comment by MassimoCappellano** [comment]
I have the same problem with italian number format, in my case float numeber, using sinitize;  delimiter for thousands: '.' and for decimal: ','.

I started from http://formvalidator.net/#data-sanitation_numberformat

Using 
```html
<input type="text" name="amount" data-validation="number" data-validation-allowing="float" data-sanitize="numberFormat"  data-sanitize-number-format="0.0,0">
```
but it doesn't work for example with 121323,34 that becomes 0,000

using instead 
```html
<input type="text" name="amount" data-validation="number" data-validation-allowing="float">
```
without sanitation and specifying ```decimalSeparator: ','``` in  ```$.validate({})``` work, but not using sanitize

Here the example http://jsfiddle.net/MassimoCappellano/kphchtr6/1/

**Comment by ray-print** [comment]
Almost done with a fix for this -- the input value needs to be unformatted before it can be used for validation and before it is re-sanitized.
Numeral.js has not been updated in over a year and a half...not sure if it makes sense to continue supporting?
Another issue came up while working on this -- the "escape" sanitization will work correctly the first time, but it will escape input multiple times upon repeated blur.
