### ISSUE TITLE
E-mail validation does not seem to validate domain correctly

### ISSUE THREAD

**Issue by meethoss** [victorjonsson/jQuery-Form-Validator#325]
I enter some random letters ("ww") and attempt to submit, it warns me I need an "@". I enter another letter and attempt to submit and it submits.

Looking at the code I can see that it is checking for an "@" and then validating the domain and from a visual check it looks correct, so not quite sure why it's not working.

**Comment by victorjonsson** [comment]
Could you provide me with your code please.

**Comment by meethoss** [comment]
Hi Victor,

I can't attach anything here. I will send you an E-mail with the HTML output. Unfortunately the project I am working on is not live and I cannot share with you the credentials to test this out. I'm not sure how much use the code will be but give it a look and let me know.

Many thanks for your help.

Kind Regards,

Steve

**Comment by meethoss** [comment]
Hi Victor,

I appreciate your help with this so far and am not sure if you received the last piece of code. The issue is there even with a very basic example (see below). Please could you look into this?

Kind Regards,

Steve


<!DOCTYPE html>
<html lang="en-GB">
	<head>
	<meta charset="UTF-8">
		<title>HELP & SUPPORT</title>
		
		<script src="https://code.jquery.com/jquery-1.8.2.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.8/jquery.form-validator.min.js"></script>
	</head>
	<body class="yui-skin-sam yui3-skin-sam">
		<div class="help_content-section help_content-section-contact-form">
			<h3 class="help_content-section-title">Please fill in your contact details below:</h3>
			<form id="help_content-section-contact-form">
				<label id="first_name_label">
					<span>First Name</span>
					<input type="text" name="first_name" id="first_name" title="First Name" /> <span class="mandatory">*</span>
				</label>
				<label id="last_name_label">
					<span>Last Name</span>
					<input type="text" name="last_name" id="last_name" title="Last Name" /> <span class="mandatory">*</span>
				</label>
				<label id="email_label">
					<span>E-mail Address</span>
					<input type="email" name="email" id="email" title="E-mail Address" required="required" /> <span class="mandatory">*</span>
				</label>
				<label id="username_label">
					<span>Username</span>
					<input type="text" name="username" id="username" title="Username" /> <span class="mandatory">*</span>
				</label>
				<label id="message_label">
					<span>Your Message</span>
					<textarea name="message" id="message" title="Your Message" rows="4" cols="72"></textarea> <span class="mandatory">*</span>
				</label>
				<label id="remember_label">
					<span>Remember me (do not tick on shared device)</span>
					<input type="checkbox" name="remember" id="remember" title="Remember me (do not tick on shared device)" />
				</label>
				<span class="mandatory_message">* Mandatory field</span>
				<button type="submit" form="help_content-section-contact-form" id="submit">Submit</button>
			</form>
			<script>
				// Validate the form
				$.validate({
					modules : 'html5',
					form : 'help_content-section-contact-form'
				});
			</script>
		</div>
	</body>
</html>

**Comment by victorjonsson** [comment]
You have an incorrect reference to the form

$.validate({ modules : 'html5', form : '*#*help_content-section-contact-form'});


2015-10-28 12:32 GMT+01:00 Stephen Pickett <notifications@github.com>:

**Comment by meethoss** [comment]
Ah, brilliant - thanks very much, I hadn't realised it was looking for the ID in the same format as jQuery/CSS - should have realised that.

Many thanks for your help, I really appreciate it!

Kind Regards,

Steve

**Comment by victorjonsson** [comment]
np
