### ISSUE TITLE
Required fields validation message

### ISSUE THREAD

**Issue by Igloczek** [victorjonsson/jQuery-Form-Validator#328]
Don't you think that displaying "You have not answered all required fields" message on every type of input might be not so UX friendly? It looks weird when few text fields/checkboxes in row has that type of error.

![Form](http://i.imgur.com/HuVsIyx.png)

IMO only radio buttons should use this type of msg, every other might have something like "This field is required".

**Comment by victorjonsson** [comment]
Yes, I agree. The error message "You have not answer...." is intended to be used when having all error messages displayed together upon form submit. Thus there must exist two different generic messages, one referring to a specific input and another one referring to the form submission.

As a quick fix you can override the `requiredFields`  property in the language object.

```js
$.validate({
   language: {
     requiredFields: "This field is required"
   }
});
```

**Comment by Igloczek** [comment]
Ok, I'll try to create pull request with this update.

**Comment by victorjonsson** [comment]
Sound great. I think it will require some serious refactoring... Maybe you would like to propose a possible solution before you implement it? This kind of change would require backwards compatibility. It's also important that the change caters to the idea of ease-of-use, it should not require programming skills to use the plugin (general knowledge about the web and html/js/css should be enough).

**Comment by Igloczek** [comment]
@victorjonsson Check if you like this solution - 6d804e8

**Comment by victorjonsson** [comment]
It's great! The only thing is that we don't have translations for requiredField**s** in all languages. Could you do a check that the property exists in the language object. Something like this

```js
errorMessageKey: function(config) { 
      var useGeneralMessage = config.errorMessagePosition === 'top' || config.errorMessagePosition === 'custom';
      if ( useGeneralMessage && config.language['requiredFields'] ) {
        return 'requiredFields';
      }
      else {
        return 'requiredField';
      }
   }
}
```

It's important that you don't do a strict comparison on `config.language['requiredFields']` in the if-statement. That way I can add the property to all language files with an empty string as value and a todo-comment stating that it needs to be translated, hoping that someone will pick it up and translate it eventually.

**Comment by Igloczek** [comment]
All missing translations added - big thanks for great translations packages to Magneto community!
