### ISSUE TITLE
Password and password confirmation validation events

### ISSUE THREAD

**Issue by aenciso** [victorjonsson/jQuery-Form-Validator#341]
Go to the form example at http://formvalidator.net/#reg-form and follow these steps:

1. Go to Password field and type in: 1234!
2. Now go to Repeat password and type in: 1234!!

 "Input values could not be confirmed" error message is displayed

3. Go back to Password field and type in: 1234!!

The error message should dissapear as soon as you type in the right password. At the moment only dissapears onBlur.

The following is an example as how it should be:

1. Go to E-mail field and type in: abc
2. Tab to another field

"You have not given a correct e-mail address" error message is displayed

3. Go back to E-mail field and type in: abc@abc.com
As soon as you input a correct email the error dissapears, not on blur

According to the standard form behaviour, Password and Repeat password fields should validate in the same way as other fields.

**Comment by treiber** [comment]
I have another issue in the same vein:

1. Go to Password field and type in: 1
    -> Error Message 'Very Bad'

2. Go to repeat password and type: 1

3. Go back to first Password Field
   -> Repeat Password field is set valid. Shouldn't this be invalid as well?

I get that it is only validating wether it is equal to the first password field, but shouldn't it also take into account wether the first password field is valid in the first place?
