### ISSUE TITLE
Using ASP.Net/Bootstrap 3 with data-validation-help

### ISSUE THREAD

**Issue by robertj98** [victorjonsson/jQuery-Form-Validator#342]
I am using a form in ASP.NET 4.0 and Bootstrap 3

For a field declared in ASP.NET as

 TextBox ID="txtCM60SEQNO" clientIDMode="static" cssclass="form-control  val-integer " 
               data-validation="number" 
               data-validation-allowing="range[1;1000]" 
               data-validation-help="Please give us some more information"
               data-validation-error-msg="You did not enter a valid sequence"
               name="txtCM60SEQNO"

When I add the data-validation-help="Please give us some more information" attribute, it fails with 

Error: Syntax error, unrecognized expression: .jquery_form_help_ctl00$contentColumns$content_glencom_newsticker$txtCM60SEQNO

In the generated HTML, the textbox is rendered as

<input name="ctl00$contentColumns$content_glencom_newsticker$txtCM60SEQNO" value="10" id="txtCM60SEQNO" class="form-control  val-integer  has-help-txt" data-validation="number" data-validation-allowing="range[1;1000]" data-validation-help="Please give us some more information" data-validation-error-msg="You did not enter a valid sequence" type="text">

Is this something to do with the name= attribute generated by ASP.NET conflicting with the plugin?

Robert

**Comment by victorjonsson** [comment]
Yes, so it seems. But the plugin should not put any constraints on input names, that's bad. I'll add this as a feature request.

**Comment by robertj98** [comment]
Victor,
Thanks for your quick response.
Your plugin is very impressive and should fit in well with our future development.
Robert
