### ISSUE TITLE
File validation 

### ISSUE THREAD

**Issue by Nageshwari-p** [victorjonsson/jQuery-Form-Validator#348]
File validation MIME TYPE is working in LINUX but not working in WINDOWS 

please help me to fix this .

**Comment by victorjonsson** [comment]
What browser are you using?

**Comment by Nageshwari-p** [comment]
chrome ,firefox, safari

**Comment by victorjonsson** [comment]
What version of Windows? What does the javascript console say? 

(btw, safari on windows?)

**Comment by Nageshwari-p** [comment]
Trying to upload a file with mime type application/zip which is not allowed

yes but its cross browse compatibility

**Comment by victorjonsson** [comment]
Okey, so what does the js-console say?

**Comment by Nageshwari-p** [comment]
im sorry  JavaScript console is like this  "Trying to upload a file with mime type  which is not allowed"

please help me to fix its urgent

**Comment by victorjonsson** [comment]
Could you provide me with the following:

- The code of your form
- The windows version you're testing on
- The version number of jQuery Form Validator that your'e using.

**Comment by Nageshwari-p** [comment]
code : `<input data-validation="mime required size" data-validation-allowing="zip, rar" data-validation-max-size="50M" data-validation-error-msg="Please upload doc" data-validation-error-msg-mime="upload only below specified type files" data-validation-error-msg-size="You can not upload file larger than 50mb" onchange="get_extension(this.value)" type="file" name="study_material[attachment]" id="study_material_attachment">'

window 7

Jquery form validatio :  @version 2.2.83

**Comment by Nageshwari-p** [comment]
code

<input data-validation="mime required size" data-validation-allowing="zip,
rar" data-validation-max-size="50M" data-validation-error-msg="Please
upload doc" data-validation-error-msg-mime="upload only below specified
type files" data-validation-error-msg-size="You can not upload file larger
than 50mb" onchange="get_extension(this.value)" type="file"
name="study_material[attachment]" id="study_material_attachment">


window 7

Jquery form validatio :  @version 2.2.83

On Thu, Nov 26, 2015 at 12:05 AM, Victor Jonsson <notifications@github.com>
wrote:

> Okey, so what does the js-console say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorjonsson/jQuery-Form-Validator/issues/348#issuecomment-159696154>
> .
>



-- 
Nageshwari | Software Developer - UI  |  www.langoor.com |  @langoor
<http://www.twitter.com/langoor> | Facebook
<http://www.facebook.com/langoor> | LinkedIn
<http://www.linkedin.com/companies/langoor>

**Comment by victorjonsson** [comment]
What do you man by "yes but its cross browse compatibility". Are you running explorer in some sort of cross browser compatibility mode?

**Comment by Nageshwari-p** [comment]
no

On Thu, Nov 26, 2015 at 1:26 PM, Victor Jonsson <notifications@github.com>
wrote:

> What do you man by "yes but its cross browse compatibility". Are you
> running explorer in some sort of cross browser compatibility mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorjonsson/jQuery-Form-Validator/issues/348#issuecomment-159840580>
> .
>



-- 
Nageshwari | Software Developer - UI  |  www.langoor.com |  @langoor
<http://www.twitter.com/langoor> | Facebook
<http://www.facebook.com/langoor> | LinkedIn
<http://www.linkedin.com/companies/langoor>

**Comment by victorjonsson** [comment]
As a quick fix you could try to change from "mime" to "extension"

**Comment by Nageshwari-p** [comment]
Thank you for support its working . thank you very much
