### ISSUE TITLE
Number validation

### ISSUE THREAD

**Issue by Nageshwari-p** [victorjonsson/jQuery-Form-Validator#353]
I need a number validation should not accept 0 .

please help me on this

**Comment by victorjonsson** [comment]
http://www.formvalidator.net/#default-validators_numbers

```html
<input type="text" data-validation="number" data-validation-allowing="range[1;9007199254740991]">
```

**Comment by Nageshwari-p** [comment]
thanks for the help .

i already used range , we only required starting num should be one and it should be infinity

**Comment by victorjonsson** [comment]
Computers don't understand infinity :) 9007199254740991 Is the highest integer value my browser can handle :)
