### ISSUE TITLE
about toggleDisabled module problem

### ISSUE THREAD

**Issue by DeadLion** [victorjonsson/jQuery-Form-Validator#363]
it just work when there has type=submit  in a form,but most time we use ajax submit . so we don't use default submit. 
why not find the element by class
like this:
```
  var d = function (a, b) {
            "disabled" == b ? a.find('.validation-submit').addClass("disabled").attr("disabled", "disabled") : a.find('.validation-submit').removeClass("disabled").removeAttr("disabled")
        }, e = !1;
```

then we can use <a></a> or type=button whatever we just need to add class="validation-submit" to an element .

AND  jQuery-Form-Validator is very awesome! thank you so much!

**Comment by victorjonsson** [comment]
My suggestion to you would be to use the native submit-event.

```js
$('#my-form').on('submit', function() {
   // do ajax stuff...
   return false; // prevent default behaviour... 
});
```
