### ISSUE TITLE
Validator displays a blank error message on keyup and blur

### ISSUE THREAD

**Issue by carlos-max** [victorjonsson/jQuery-Form-Validator#373]
The validator displays a blank error:

- 1: After filling a required field and changing focus to another field (Using tab key or clicking);
- 2: On keyup, when the validator already displayed a validation error message;

1:
![1](https://cloud.githubusercontent.com/assets/16707756/12333423/49c5399e-badb-11e5-9efc-fd718a196317.gif)

2:
![2](https://cloud.githubusercontent.com/assets/16707756/12333433/561c6a14-badb-11e5-868f-538ba83c60d3.gif)

The HTML:
```
<body>
<p id="error-msg">
		
        <form id="form-cliente" class="tabs" method="post" action="php/cliente_cadastro.php">

        <input type="text" id="cnpj" name="cnpj"  data-validation="required" data-validation-error-msg="O campo CNPJ é obrigatório!">
```

The script:
```
$(document).ready(function() {
.....
            var $messages = $('#error-msg');
                        
            $.validate({
                form : '#form-cliente',
                modules: 'html5',                                              
                validateOnBlur : true,                
                showHelpOnFocus : false,
                addSuggestions : false,
                errorMessagePosition : $messages,
                scrollToTopOnError : true,
            });
});
```

**Comment by carlos-max** [comment]
Forgot to write the input part in the HTML:

<input type="text" id="cnpj" name="cnpj"  data-validation="required" data-validation-error-msg="O campo CNPJ é obrigatório!">

**Comment by victorjonsson** [comment]
You can use the pseudo class `:empty` as a quick fix until the issue gets resolved.

```css
#errorMessages:empty {
   display: none
}
```

**Comment by larssn** [comment]
In my case it was:
`.form-error:empty {
    display: none
}`

**Comment by carlos-max** [comment]
Larssn fix worked for me.

Thanks for the support guys!

**Comment by larssn** [comment]
This causes further upset in Chrome 48.
It doesn't respect "display: none" for these .form-error(s), and they thus still take up space in the DOM. Requesting a patch for this issue, in case the next release is long off.

**Comment by larssn** [comment]
Thanks for the fix!
