### ISSUE TITLE
isValid method's onSuccess / onError not being called

### ISSUE THREAD

**Issue by shreyasubale** [victorjonsson/jQuery-Form-Validator#375]
I have a server validated field in my setup, so i need the success callback to work. But the suucess/error callbacks are not triggering on isValid method.

**Comment by gbrennon** [comment]
:+1:

**Comment by victorjonsson** [comment]
After looking through the code I have decided not to support this.

The configuration options `onSuccess` and `onError` is meant for attaching event listeners to the event of a successful, or unsuccessful, form submission. The method `isValid()` is meant for synchronously checking if all the inputs in the form is valid (not triggering a form submission). 

The fact is that this method can't support the case of having asynchronous validators in the form (the two async validators are at the moment [server](http://www.formvalidator.net/index.html#security-validators_backend) and [dimensions](http://www.formvalidator.net/#file-validators_dimension)).

**Comment by micro-belgium-application** [comment]
Can you hint to some workaround please ?

I tried to make validation synchronous but it didn't work.

NB : you might update your documentation on isValid to specify that the following doesn't work with custom async validator :

> Notice! This method won't be able to tell if the form is valid if your'e using asynchronous validators, like the server-side validator and the image dimensions validator. In such a case you must combine the method call with the onSuccess callback.
