### ISSUE TITLE
No validation on previously disabled elements

### ISSUE THREAD

**Issue by mschlenstedt** [victorjonsson/jQuery-Form-Validator#376]
Hi,

I have a problem with elements which are disabled by default and will only be enabled by certain dependencies. These elements won't be validated. Do I something wrong or is that maybe a bug?

If needed I could provide my code.

Thanks,
Michael

**Comment by victorjonsson** [comment]
`validateHiddenInputs: true|false` http://www.formvalidator.net/#configuration_options
