### ISSUE TITLE
ASP.NET html5.js minification javascript error

### ISSUE THREAD

**Issue by MrGold** [victorjonsson/jQuery-Form-Validator#377]
Hello,

When i add  html5.dev.js   or html5.js to bundle , it causes the following error  ;

<em>Uncaught TypeError: t.each is not a function</em>

**Comment by victorjonsson** [comment]
What bundling-tool are you using? It looks as html5.js is added to the bundle before jQuery.

**Comment by MrGold** [comment]
I am using [microsoft.aspnet.web.optimization](https://www.nuget.org/packages/microsoft.aspnet.web.optimization/).  My js bundle order ;

jquery-2.2.0.js
angular.js
json3.min.js
..
..
formValidator/jquery.form-validator.min.js
formValidator/date.js
formValidator/file.js
formValidator/html5.dev.js 
formValidator/location.js
formValidator/security.js

**Comment by victorjonsson** [comment]
When do you get the error? Could provide me with the full stack trace

**Comment by MrGold** [comment]
Well, i opened this issue like 4 months ago. That time i was getting that error, now i've added html5.dev.js to the bundle and  compiled again. Voila, it is working now. I don't know how it happened, but seems like my bad here.
I close this issue. No problem here.

**Comment by victorjonsson** [comment]
np 👍
