### ISSUE TITLE
how to trigger one input valide function

### ISSUE THREAD

**Issue by zld406504302** [victorjonsson/jQuery-Form-Validator#384]
i have a mail input,i want to check mail when i click 'mail-captcha' button ,how do it ?

![pic](https://cloud.githubusercontent.com/assets/3940707/13032786/21110492-d33b-11e5-8ef1-efe1d71ea61b.png)

**Comment by victorjonsson** [comment]
What do you mean by mail-captcha? You want to validate if the form contains a valid e-mail? The you should use the email-validator http://www.formvalidator.net/#default-validators_email
