### ISSUE TITLE
getting TypeError: $.validate is not a function 	  $.validate(config);  	

### ISSUE THREAD

**Issue by BernardA** [victorjonsson/jQuery-Form-Validator#386]
Hello
For a few days now I am getting this error, which seems to indicate that form validator is not loading.
This is script:
`
src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.0/jquery.form-validator.min.js"
`

You can check this on this site (beta):

http://www.soeezauto.com/used_signup.php

Thanks

Bernard

**Comment by victorjonsson** [comment]
This was probably a local network issue
