### ISSUE TITLE
validate on single input

### ISSUE THREAD

**Issue by ahan** [victorjonsson/jQuery-Form-Validator#387]
I overwrited the lang configure, when I hit the submit, it works great
But if I validate on single input, the lang use the 'en' package
Here is my code, is there anything I configure wrong?

$.validate({
    language: validatorLang,
    modules: 'security',
})

$('#the-input').validate(function(valid, elem) {
   console.log('Element '+elem.name+' is '+( valid ? 'valid' : 'invlid'));
}, {
    language: validatorLang,
});

**Comment by victorjonsson** [comment]
Sorry but it seems that the documentation was lacking this information. The language object is actually the third parameter. 

```js
$('#the-input').validate(function(valid, elem) {
   console.log('Element '+elem.name+' is '+( valid ? 'valid' : 'invlid'));
}, {}, validatorLang);
```
