### ISSUE TITLE
Optional Number fields

### ISSUE THREAD

**Issue by haxtrujillo** [victorjonsson/jQuery-Form-Validator#388]
Number fields that are not required should not be validated, otherwise the field required to enter at least one number.

**Comment by victorjonsson** [comment]
http://www.formvalidator.net/#default-validators_optional

**Comment by haxtrujillo** [comment]
It doesn't work. I am using the html5 plugin, even setting to be optional the validator requires a number.

**Comment by ray-print** [comment]
Duplicate of #315? If so, that should be fixed in the next release.
