### ISSUE TITLE
toggleDisabled not enabling submit

### ISSUE THREAD

**Issue by penone** [victorjonsson/jQuery-Form-Validator#393]
Having an issue with the toggleDisabled option.

When the form loads the submit button is disabled - good.

When I complete the required fields on the form the submit button is still disabled.

Am using this:
```
  $.validate({
    modules : 'toggleDisabled',
	disabledFormFilter : 'form.webform-client-form-13',
	showErrorDialogs : false
	
  });
```
Where .webform-client-form-13 is a class on my form tag.

What am i doing wrong?

**Comment by victorjonsson** [comment]
I need to see the markup of the form aswell

**Comment by victorjonsson** [comment]
I'm going to close this issue soon if no more information is provided.
