### ISSUE TITLE
validate if the value changed

### ISSUE THREAD

**Issue by ahan** [victorjonsson/jQuery-Form-Validator#406]
Here is the case:
I have a User Setting page, it's a form with several fields, there is a 'name' field, its value need to be unique, so I config it with 'server validation'.
When a user come to this page to change other field, then submit, the Validator will do 'server validation' at 'name' field, then of course the 'name' field validate failed.

How can I make the Validator, don't validate the field if its value hasn't changed?

**Comment by victorjonsson** [comment]
I guess with some custom code.

```
<input id="user" data-validation-tmp="server" />
<script>
function setupValidation() {
  $.validate(...);
}

// Init validation
setupValidation();

// Re-initiate validation when username changes
$('#user').one('change', function() {
   $(this).attr('data-validation', $(this).attr('data-validation-tmp'));
   setupValidation();
});
</script>
```
