### ISSUE TITLE
Server-Side Validation Issue

### ISSUE THREAD

**Issue by Papa2k15** [victorjonsson/jQuery-Form-Validator#409]
I am currently using the security module to do some server-side validation. I currently have an input text box that checks to see if a username has already been registered. I have noticed that whenever I am typing, once the server validates the input, it loses focus. I don't know if this is currently a issue because I tried to search the repository. When the element loses focus this sort of becomes a pain for a user because if they hit back space then the browser will go back in history. Also if the user types what they want their username to be it will stop them and they will have to click back onto the input box to continue typing, I am guessing that the server binds the keyup event to the input then tells it to lose focus on validate. I am currently using three different validations on this input, one for length, another for regular expression and the last is the server. I have tried to isolate and just use the server but I was still getting the same result. Here is an example of what my input looks like:

`<input id="regusername" name="username" type="text" 
									data-validation="length custom server"
									data-validation-url="/check_avaliable_username" 
									data-validation-length="min6"
									data-validation-regexp="^[A-Za-z0-9_]+$"
									class="form-control" autocomplete="off" placeholder="Username"/>`

Is this something that I did wrong?

**Comment by Makgatho** [comment]
I have the same problem only when using the toggleDisabled module with my server-side validation. We might be experiencing the same problem

**Comment by victorjonsson** [comment]
Duplicate of #436
