### ISSUE TITLE
Problem on jquery validate and radio buttons

### ISSUE THREAD

**Issue by cretace** [victorjonsson/jQuery-Form-Validator#413]
When using $.validate (not form submit) and tabbing through form, a radio button message on the first item of a set does not clear if the second item of the pair is clicked. 
I only want to show one message such as "Choose a button"  and the user must click one or other.

**Comment by victorjonsson** [comment]
Could you please provide me with some code?

**Comment by cretace** [comment]
<div ><input type="radio"  name="rcv"  value='2'
    data-validation="required"
    data-validation-error-msg="Select an option"
   >  I wish to receive news and promotions </div>

   <div ><input type="radio"  name="rcv" value='1'
   data-validation="required"
   data-validation-error-msg="Select an option"
   >   I do not wish to receive any information</div>

I also tried with "checkbox group". 
I am doing this on interactive tabbing through fields - not on form submit.
I would like only one message to show and for that message to go away if either button is clicked.
Thanks!

**Comment by Billy-** [comment]
I believe we need a `radio_group` validator? I am trying to get this to work but can't seem to make it happen with current version :(

**Comment by Billy-** [comment]
@victorjonsson if you can confirm what you would like to do about this I would be happy to work on it.

**Comment by victorjonsson** [comment]
I'm not able to reproduce this http://jsbin.com/bezezulewi/edit?html,output

What version have you tried?

**Comment by Billy-** [comment]
I see - I was only putting validators on the first input - like checkboxes.

Can we add some documentation on radio buttons as there isn't a mention of them in the docs?

**Comment by victorjonsson** [comment]
hehe, that was actually a mistake on my part. Should not be required to add the validation-rule on all inputs. So this bug is now confirmed.

The issue here is not to introduce a new validator. The validation rule "required" should support this.

**Comment by Billy-** [comment]
Ok, for reference, [here](https://github.com/Billy-/jQuery-Form-Validator/commit/a9fd61cbff83faf4bc7fe9ffb5f3fdc40b74f062) is the validator I implemented for the purpose. It is loosely based on the checkbox group validator in that it binds a change event to the other radios in the group, so when they get changed, the whole group re-validates. Perhaps we can work this into the required validator? I can have a go, if you like?

**Comment by victorjonsson** [comment]
Please do.

**Comment by Billy-** [comment]
I see this functionality is actually already a part of the `required` validator. I will take a look & debug it now.
