### ISSUE TITLE
How to fix "Uncaught TypeError: Cannot read property 'length' of undefined" ?

### ISSUE THREAD

**Issue by viiiprock** [victorjonsson/jQuery-Form-Validator#417]
I got an error message: "Uncaught TypeError: Cannot read property 'length' of undefined" In other page without using validator, how could I fix ?
error happens at line 157 : **var a = b.val().length;**
lengthRestriction: function(b, c) {
            var d = parseInt(c.text(), 10),
                e = 0,
                f = function() {

                        var a = b.val().length;
           
                    if (a > d) {
                        var f = b.scrollTop();
                        b.val(b.val().substring(0, d)), b.scrollTop(f)
                    }
                    e = d - a, 0 > e && (e = 0), c.text(e)
                };

Thank you!

**Comment by victorjonsson** [comment]
Could you please provide me with the code that triggers the error?

**Comment by viiiprock** [comment]
Thanks victor
This is happen in other page has no trigger at line 157 : var a = b.val().length;
The page with trigger has no error.
<img width="1437" alt="screen shot 2016-03-22 at 4 12 20 pm" src="https://cloud.githubusercontent.com/assets/14918259/13946738/e8348128-f048-11e5-8461-b6e0c2e57d60.png">

**Comment by viiiprock** [comment]
Oops, I think you mean this 

$(document).ready(function() {
// Restrict presentation length
$('#presentation').restrictLength( $('#pres-max-length') );
});

**Comment by viiiprock** [comment]
Okay, thanks Victor, I fixed it.
