### ISSUE TITLE
scrollToTopOnError

### ISSUE THREAD

**Issue by alfiyan28** [victorjonsson/jQuery-Form-Validator#419]
how to scroll and show the DIV of Error Message ?
NOT scroll and show the first input

when I set scrollToTopOnError:true
![image](https://cloud.githubusercontent.com/assets/11345557/14033380/6f746f68-f24c-11e5-9e5a-6465e2620310.png)

but not scroll to div Error Message
![image](https://cloud.githubusercontent.com/assets/11345557/14033386/7f748a92-f24c-11e5-9586-cd82e75844df.png)

**Comment by victorjonsson** [comment]
This is because of a bug on formvalidator.net. It has nothing to do with the plugin itself.
