### ISSUE TITLE
Integrate with TinyMCE

### ISSUE THREAD

**Issue by alfiyan28** [victorjonsson/jQuery-Form-Validator#422]
I'm using WSYISYG tinyMCE https://www.tinymce.com/ 

when I use normal textarea, validator works well, but when I add tinyMCE the validator can't work?

**Comment by victorjonsson** [comment]
Duplicate of #324

**Comment by victorjonsson** [comment]
Here's a quick and dirty fix https://github.com/victorjonsson/jQuery-Form-Validator/issues/324#issuecomment-220016075
