### ISSUE TITLE
Custom validator error message

### ISSUE THREAD

**Issue by BenasPaulikas** [victorjonsson/jQuery-Form-Validator#423]
So we have input

    <input data-validation="blacklist email" data-validation-error-msg="Email is not correct">

And blacklist validator

    $.formUtils.addValidator({
        name: 'blacklist',
        validatorFunction: function (value, $el, config, language, $form) {
            return email_status == 1;
        },
        errorMessage: "Service is suspended",
        errorMessageKey: 'badBlacklist'
    });

However we are receiving "Email is not correct" not errorMessage from blacklist validator. Any ideas why ?

**Comment by victorjonsson** [comment]
Because you're also validating the e-mailaddress `data-validation="blacklist email"`

**Comment by BenasPaulikas** [comment]
So there's no way I can add custom error message for blacklist ? In conjuction with email ?

**Comment by victorjonsson** [comment]
I'm not able to reproduce this, it works as expected http://jsbin.com/biseyijasa/1/edit?html,js,output

What version of the plugin are you using?

**Comment by victorjonsson** [comment]
If you have defined "data-validation-error-msg" you'll always get that error message. If you would omit the attribute it would show the error message coming from the first failed validator.

You should be able to define an error message for the blacklist validator, on the input element.

```html
<input 
   data-validation="blacklist email"
   data-validation-error-msg-blacklist="Blacklist error message..."
   data-validation-error-msg-email="Email error message..." />
```
