### ISSUE TITLE
Using undefined validator

### ISSUE THREAD

**Issue by QuentinVaut** [victorjonsson/jQuery-Form-Validator#429]
Hello, thanks for this great plugins but I 've problem, my browser say : 
Using undefined validator for all my modules.
![erroformvalidation](https://cloud.githubusercontent.com/assets/7362377/14812708/9b9defc2-0b9e-11e6-8e0f-c6070afc6e55.PNG)
My code : http://pastebin.com/3BZ6bmb2

When I use this plugin with classic HTML work fine but when I use it on ASPX page I've these errors.
All files for modules are correctly loaded by browser.

**Comment by victorjonsson** [comment]
What version of the plugin are you using? Can you confirm that the module files are loaded in the console. They must be located in `js/plugins/form-validator/` for your code to work.

**Comment by victorjonsson** [comment]
You could try thisto check that the plugin can load the module files

```html
 <script type="text/jscript" src="js/jquery.js"></script>
    <script type="text/jscript" src="js/plugins/form-validator/jquery.form-validator.min.js"></script>
    <script>
     
     $.formUtils.loadModules('location, date', null, function() {
         alert('modules loaded...');
     }); 
    </script>
````

**Comment by QuentinVaut** [comment]
`  <script>

        $.formUtils.loadModules('location, date, security, file', null, function () {
            alert('modules loaded...');
        }); 
    </script>`

Say "modules loaded". I use the last release on master branch.

**Comment by victorjonsson** [comment]
Could you also try this and check what you can see in the console

```js
$.formUtils.loadModules('location, date, security, file', null, function () {
   console.log('modules loaded...');
   console.log($.formUtils.validators);
}); 
```

**Comment by QuentinVaut** [comment]
My result : 

`Object {validate_email: Object, validate_domain: Object, validate_required: Object, validate_length: Object, validate_url: Object…}
`

**Comment by victorjonsson** [comment]
Sorry I need to see them all.. 

```js
$.formUtils.loadModules('location, date, security, file', null, function () {
   console.log('modules loaded...');
   console.log( Object.keys($.formUtils.validators) );
}); 
```

**Comment by QuentinVaut** [comment]
Show all modules are loaded : 

```
modules loaded...
test.aspx:249 ["validate_email", "validate_domain", "validate_required", "validate_length", "validate_url", "validate_number", "validate_alphanumeric", "validate_custom", "validate_date", "validate_checkbox_group", "validate_country", "validate_federatestate", "validate_longlat", "validate_time", "validate_birthdate", "validate_mime", "validate_extension", "validate_size", "validate_dimension", "validate_spamcheck", "validate_confirmation", "validate_creditcard", "validate_cvv", "validate_strength", "validate_server", "validate_letternumeric", "validate_recaptcha"]
```

**Comment by victorjonsson** [comment]
Hm.. could you try this:

```js

var setupValidation = function() {
  $.validate({
    lang: 'fr',
    onModulesLoaded: function () {
      $('#country').suggestCountry();
    }
  });

  // Restrict presentation length
  $('#presentation').restrictLength($('#pres-max-length'));  
};

$.formUtils.loadModules('location, date, security, file', null, setupValidation);

```

**Comment by QuentinVaut** [comment]
Yes, it works fine ! Thanks you !

**Comment by ManuSbd** [comment]
Hey,

I try this way but i can't load modules i'm getting errors, I try yor code "See them all":

> date.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ date.js:9(anonymous function) @ date.js:9(anonymous function) @ date.js:9(anonymous function) @ date.js:9
location.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ location.js:9(anonymous function) @ location.js:9(anonymous function) @ location.js:9(anonymous function) @ location.js:9
file.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ file.js:9(anonymous function) @ file.js:9(anonymous function) @ file.js:9(anonymous function) @ file.js:9
security.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ security.js:9(anonymous function) @ security.js:9(anonymous function) @ security.js:9(anonymous function) @ security.js:9
(index):127 modules loaded...
(index):128 Uncaught TypeError: Cannot read property 'validators' of undefined

When I try your next code I get this

> location.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ location.js:9(anonymous function) @ location.js:9(anonymous function) @ location.js:9(anonymous function) @ location.js:9
date.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ date.js:9(anonymous function) @ date.js:9(anonymous function) @ date.js:9(anonymous function) @ date.js:9
security.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ security.js:9(anonymous function) @ security.js:9(anonymous function) @ security.js:9(anonymous function) @ security.js:9
file.js:9 Uncaught TypeError: Cannot read property 'addValidator' of undefined(anonymous function) @ file.js:9(anonymous function) @ file.js:9(anonymous function) @ file.js:9(anonymous function) @ file.js:9
(index):127 Uncaught TypeError: $.validate is not a function

Any idea? I change "null" for the route where is form-validator

Thanks.
