### ISSUE TITLE
New language + error in es

### ISSUE THREAD

**Issue by ManuSbd** [victorjonsson/jQuery-Form-Validator#435]
Hey!

I write a new language for this nice pluggin.

Its catalan maybe not a lot of people need it but.. it's something (rename it to ca.js)
[ca.txt](https://github.com/victorjonsson/jQuery-Form-Validator/files/250164/ca.txt)

Also i see an error into es.js language

this

> badUKVatAnswer: 'No número VAT proporcionado no es válido para el Reino Unido',

should be

> badUKVatAnswer: 'El número VAT proporcionado no es válido para el Reino Unido',

Cheers!

**Comment by victorjonsson** [comment]
Thanx!
