### ISSUE TITLE
ReCaptcha is broken.

### ISSUE THREAD

**Issue by arkin-** [victorjonsson/jQuery-Form-Validator#445]
Hi, Recaptcha is broken, it doesn't seem to validate whether or not the user is validated.

    <input data-validation="recaptcha" data-validation-recaptcha-sitekey="6LfNXSETAAAAAFwZK9C_5WjM_tswGQr44N8_o-Lh">

**Comment by victorjonsson** [comment]
What does the js console say?

**Comment by arkin-** [comment]
Absolutely nothing, the other fields validate correctly too.

![screenshot 2016-05-31 15 10 15](https://cloud.githubusercontent.com/assets/1921583/15677348/d5697492-2741-11e6-8316-e23ad35edf4e.png)

**Comment by arkin-** [comment]
I might have mis-understood the use case as the documentation is "light".

I was hoping that it would detect the captcha has not passed and prevent the form submission.

**Comment by victorjonsson** [comment]
It's supposed to... I will take a look at this as soon as possible

**Comment by victorjonsson** [comment]
Fixed in #452

**Comment by arkin-** [comment]
Thank you @victorjonsson, I'll give this a go.
