### ISSUE TITLE
Getting SyntaxError on data-validation-req-params

### ISSUE THREAD

**Issue by ZenitramPRO** [victorjonsson/jQuery-Form-Validator#453]
I'm following the tutorial for serverside validation on setting up additional parameter.

I'm getting SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data.

PHP
```
<?php
  $json = json_encode(array('user'=>$user->get('ID')));
?>
<p>
  <strong>E-mail:</strong>
  <input type="email" name="check-email" data-validation="server"
        data-validation-url="/validate-form-input.php"
        data-validation-param-name="email"
        data-validation-req-params="<?php echo $json ?>" />
</p>
```

**Comment by victorjonsson** [comment]
There seems to be an error in the documentation. The req-params attribute needs to have apostrophes instead of quotations.

```html
data-validation-req-params='<?php echo $json ?>'
```

**Comment by ZenitramPRO** [comment]
wow! it's now working. my practice is to use double quotes in php. Thank you!

**Comment by victorjonsson** [comment]
JSON must use quotations and therefor the HTML markup will become invalid when inserting a json string inside quotations... I will make sure to update the documentation

**Comment by ZenitramPRO** [comment]
I'll put that in mind. Thank you for helping me!
