### ISSUE TITLE
add support for .partner domain in email validation

### ISSUE THREAD

**Issue by xxvii27** [victorjonsson/jQuery-Form-Validator#454]
add support for .partner domain in email validation

**Comment by xxvii27** [comment]
might be better to validate domain from this list directly instead:
http://data.iana.org/TLD/tlds-alpha-by-domain.txt which is updated continuously by the IANA

**Comment by victorjonsson** [comment]
Why was this closed?

**Comment by xxvii27** [comment]
Just updated the lib, and solved my issue.
