### ISSUE TITLE
Validation server entering loop when the server returns true

### ISSUE THREAD

**Issue by planweb** [victorjonsson/jQuery-Form-Validator#460]
The validation behaves as expected when it is not valid, that is, when the server returns {valid: false}, but when he returns {valid: true}, is entering loop repeating the request to the server constantly.

In the video below I show you what's going on, could help me to see if I'm doing something wrong or if it's a bug of the plugin?

https://youtu.be/n0xqrNKgwYk

**Comment by planweb** [comment]
The last update you did correct this problem? Because I downloaded the most current files and tested but the problem remains the same, as shown in the video.

**Comment by victorjonsson** [comment]
Could you please provide me with your form markup.

**Comment by victorjonsson** [comment]
I have now tried a multitude of different setups but not been able to reproduce this bug (using version 2.3.26)

**Comment by planweb** [comment]
I discovered the cause of the problem was the way I was including the scripts. My initial idea was in the configuration file to include the plugin using the method $ .getScript of jquery, but for some reason this caused the reported bug.

When did the inclusion of scripts in HTML separately, it functioned normally.

Here's what I had done and that my thought was to run:

https://codepen.io/anon/pen/GqraAy
