### ISSUE TITLE
Cannot set showErrorDialogs to false without toggleDisabled

### ISSUE THREAD

**Issue by francis6425** [victorjonsson/jQuery-Form-Validator#462]
I'm able to hide the error message with the following statement
$.validate({modules: 'toggleDisabled', showErrorDialogs: false, validateOnBlur: false});

But if I don't want to disable the submit button by having the module toggleDisabled removed, the error message will be shown even with the showErrorDialog:false.

Is it a bug or did I missed something out.

**Comment by victorjonsson** [comment]
The attribute `showErrorDialog` is only used by the module `toggleDisabled`. See http://www.formvalidator.net/#configuration_position and the section about custom error message callback

**Comment by francis6425** [comment]
Thanks for your clarification.
However I also notice that if i have required input and optional input in the form,
when the optional input is updated, the submit still remains disabled.
To enable the button i will always need to trigger the blur event of those required field.

**Comment by victorjonsson** [comment]
I'm not able to reproduce this bug. http://jsbin.com/roxukihusu/edit?html,js,output

Could you provide me with your form markup

**Comment by victorjonsson** [comment]
This should not be an issue as of 2.3.72
