### ISSUE TITLE
Unable to validate form with SpringBoot/MVC/Thymelaf/Bootstrap3

### ISSUE THREAD

**Issue by mscaldas2012** [victorjonsson/jQuery-Form-Validator#471]
Update - I was able to make everything work, by manually calling $.validate on my button:
&lt;button type="submit" class="btn ban-primary" onclick="$.validate()"&gt;Save&lt;/button&gt;

(it was my understanding this was not necessary!)
Hi,
I've been trying to have a simple form validated using jQuery-form-validator, but the javascript never fires.

Could anyone confirm that query-form-validator works with my architecture? - SpringBoot / SpringMVC, Thymeleaf, Bootstrap3.

thanks,
Marcelo

**Comment by victorjonsson** [comment]
I need to see the entire markup of the form to give any real comment on this.

This plugin works regardless of how what tech is running your backend.

**Comment by mscaldas2012** [comment]
Would you mind checking my project? I've uploaded it to github - https://github.com/mscaldas2012/chronicApps.

Right now, I have the form working, but really curious as to why is not firing the validate automatically.

thanks,
