### ISSUE TITLE
[jQuery 3.1.0] Password confirmation custom error message

### ISSUE THREAD

**Issue by Tklaversma** [victorjonsson/jQuery-Form-Validator#478]
Hi,

I was wondering why the following does not work? I would like to adjust the default error message of the confirmation password field.

```
<input type="password" name="pwd_confirmation" value="" required
       data-validation="length"
       data-validation-length="min8">

<input type="password" name="pwd" value="" required
       data-validation="confirmation"
       data-validation-error-msg-confirmation="MY CUSTOM MESASGE">
```

Hope you guys can help me out.
Thanks in advance!

**Comment by victorjonsson** [comment]
Each input must have its own parent element.

http://jsbin.com/razinikaci/edit?html,console,output

**Comment by Tklaversma** [comment]
Ok, so I [updated](http://jsbin.com/towuxuzixu/1/edit?html,console,output) your jsbin and the problem seem to be jQuery 3.1.0.

When I use jQuery 3.1.0 I do not see my custom error message, but when I switch to jQuery 1.10.* it does work.

Can you help me out?

**Comment by victorjonsson** [comment]
Ouch! I will check it out....

2016-08-09 11:25 GMT+02:00 Tklaversma <notifications@github.com>:

**Comment by victorjonsson** [comment]
Hm.. what browser are you using? The jsbin works as expected for me in latest version of Chrome http://jsbin.com/kumiwuvali/edit?html,console,output

**Comment by Tklaversma** [comment]
>Hm.. what browser are you using? The jsbin works as expected for me in latest version of Chrome http://jsbin.com/kumiwuvali/edit?html,console,output

Versie 52.0.2743.116 (64-bit)

**Comment by victorjonsson** [comment]
Well, I don't know what the problem is here. You'll have to explain in deep detail what you're doing and how the behaviour of the plugin differs from what you expect.

**Comment by Tklaversma** [comment]
>Well, I don't know what the problem is here. You'll have to explain in deep detail what you're doing and how the behaviour of the plugin differs from what you expect.

On your JSFiddle it works :S.. Then its probably one of the jQuery Form properties I've set that blocks this message or something.

Anyway, thanks!

**Comment by Tklaversma** [comment]
So I just found out that `validationErrorMsgAttribute: ''` was the problem.. I've removed this and now it works.

**Comment by victorjonsson** [comment]
Great!
