### ISSUE TITLE
Adding data-validation attribute dynamically does not seem to work.

### ISSUE THREAD

**Issue by CodeBroJohn** [victorjonsson/jQuery-Form-Validator#491]
Hello I am trying to add data-validation required to a textarea dynamically. 

`$("#delComment").attr({'required':"true", 'data-validation':"required"});`

When I review the code in the developer tools the attribute is there but it does not validate properly. 

Anyone else experience this issue?

**Comment by victorjonsson** [comment]
Could you provide me with some more of your code?

**Comment by CodeBroJohn** [comment]
No problem. 

Here is a codepen link of an example of the issue: [http://codepen.io/CodeBroJohn/pen/bZPPKW](url)

So basically if a certain option is selected in my select, I use jquery to add the required attributes for data validation to work. 

In this example I am adding those attributes to a textarea id delComment. 

However it seems to not work correctly. You can verify that in the codepen example because when the option is selected you can go in the developer console and see the attributes are added. However, when you take focus away from the textarea the border does not change and the validation error message does not display.

**Comment by victorjonsson** [comment]
When using validateOnBlur (which is default) you must re-initiate the validation after that you've made changes to the form markup.

Here I have modified your example so that it works as expected http://codepen.io/anon/pen/rLXbzQ

**Comment by CodeBroJohn** [comment]
Thanks, worked perfectly.
