### ISSUE TITLE
custom Validation

### ISSUE THREAD

**Issue by osleonard** [victorjonsson/jQuery-Form-Validator#495]
```
<script>
        var config = {
            // ordinary validation config
            form : '#login-form',
            // reference to elements and the validation rules that should be applied
            validate : {
                'email' : {
                    validation : 'email, alphanumeric',
                    length : '5-12',
                    '_data-sanitize': 'trim'
                },
                'password' : {
                    validation : 'length, strength',
                    strength : '3',
                    length : 'min10'
                }
            }
        };

        $.validate({
            modules : 'jsconf, security, toggleDisabled',
            onModulesLoaded : function() {
                $.setupValidation(config);
            }
        });

    </script>
```

I have the above code however the setupValidation doesnt seems to be available in the jquery.form-validator.min.js. on click of submit button the validation doesnt work.

**Comment by victorjonsson** [comment]
I'm not able to reproduce this http://jsbin.com/rokuyoyoma/edit?html,js,console,output . I need to see how you include the scripts on your page.

**Comment by osleonard** [comment]
I am using this in a laravel application 

` {!! Form::open(array('route' => 'session.login','id'=>'login-form')) !!}
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="ti-email"></i></span>
                                <input type="text" class="form-control" placeholder="Email" name="email">
                            </div>
                        </div>

                        <hr class="hr-xs">

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="ti-unlock"></i></span>
                                <input type="password" class="form-control" placeholder="Password" name="password">
                            </div>
                        </div>

                        <button class="btn btn-primary btn-block" type="submit">Login</button>

                    {!! Form::close() !!}
`

Above is the form.

Downloaded the script and then combined with my existing javascript files with gulp.

**Comment by victorjonsson** [comment]
The modules are loaded asyncronhously, eg http://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jsconf.js . In your case you have to include them in the minified script that you're creating wioth gulp

**Comment by osleonard** [comment]
Hi Victor, 

I have included the new script shared, still same issue, however I noticed that the version of jquery I am using is different
2.2.0 - Mine
1.10.2 - One used

Could this be the issue ?

**Comment by victorjonsson** [comment]
It has nothing to do with jQuery version http://jsbin.com/xeditefeci/edit?html,js,console,output

What do you mean by "new script shared"? All module files has to be included in your bundle. Could you show me your gulp configuration.

**Comment by osleonard** [comment]
"New script shared" - I meant this file that I had to include -   http://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jsconf.js 

`var elixir = require('laravel-elixir');
/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */


elixir(function(mix) {

  mix.scripts([
      'app.js',
      'jquery.form-validator.min.js',
      'jsconf.js',
    'custom.js',
    'summernote.min.js',
    'bootstrap-datepicker.min.js',
    'select2.min.js',
    'jquery.dataTables.min.js',
    'dataTables.bootstrap.js',
    'dataTables.buttons.min.js',
    'buttons.bootstrap.min.js',
    'jszip.min.js',
    'pdfmake.min.js',
    'vfs_fonts.js',
    'buttons.html5.min.js',
    'buttons.print.min.js'
      
    ],'./public/js/final.js', './public/js/predefined');

 mix.phpUnit();
 mix.phpSpec();

});


`
