### ISSUE TITLE
Request to allow the plugin to be called on jQuery objects containing a <form> directly

### ISSUE THREAD

**Issue by makbeta** [victorjonsson/jQuery-Form-Validator#498]
This plugin is quite powerful, thank you for all your hard work. 

I was wondering if the plugin can be modified to allow the validate function be called on a jQuery object and return one as well, to allow for chaining. I would be happy to help work out some of the code. The only problem is that there are `$.fn.validate()` that is called only on inputs and `$.validate()` that's called without the object. 

The use case for this is: I have 3 forms on a page that I do multiple things to, including validation. So I have a function like this:

```
$.fn.signUp() {
  var $myForms = this;
  $myForms.validate().doSomethingElse();
}
```

I would like to reuse this plugin for validation on the jQuery objects that I already have. Currently the plugin only takes in 'form:' option in the configuration, but that seems very inefficient, as the plugin has to do repeated work of searching the whole DOM for the elements again. 

My initial thoughts were to update `$.validate()` function to check if this is a jQuery form object then use it , otherwise to use `$(conf.form)`. The only hitch is the other `$.fn.validate()` input, which seems a bit of misnomer, and renaming it to `$.fn.validateInput()` is not possible as there is already that function there as well.  I don't know all the history of the plugin and reasoning for those choices, but wanted to file this request in case someone else is interested in this approach as well.

**Comment by victorjonsson** [comment]
http://www.formvalidator.net/#advanced
