### ISSUE TITLE
Not able to allow '+' with numbers

### ISSUE THREAD

**Issue by ivishalvarshney** [victorjonsson/jQuery-Form-Validator#507]
I just wanted to create validated fields for phone number with '+' at begining of phone number

But following is not working to allow '+' with numbers
`<input class="form-control" data-validation="required number" name="phone" type="text" data-validation-allowing="+">`

`<input class="form-control" data-validation="required number" name="phone" type="text" data-validation-ignore="+">`

How to acheive this ?

**Comment by victorjonsson** [comment]
Have you tried http://www.formvalidator.net/#default-validators_ignore

**Comment by ivishalvarshney** [comment]
Yes, I have already tried this, syntax i have used is already in question description.

Even it is not working in library. Please have a look to snapshot below.
![formvalidator](https://cloud.githubusercontent.com/assets/12258544/19080053/7363bb82-8a73-11e6-9a71-05d6c1f613f4.png)

**Comment by victorjonsson** [comment]
The latest version on cdn has a bug effecting this feature. What version are you using?

**Comment by victorjonsson** [comment]
This is however fixed in latest release:

http://jsbin.com/vanecicofu/edit?html,js,output
