### ISSUE TITLE
Custom error message markup in inlineErrorMessageCallback duplicating

### ISSUE THREAD

**Issue by LinzardMac** [victorjonsson/jQuery-Form-Validator#510]
I am finding that when I setup a custom error message using the inlineErrorMessageCallback function, the actual function is run twice - once before the error message is generated and immediately after it is. This makes it difficult to test the validity of the field in order to return the proper type of container / html markup for the message. 

Below is the code I am using and I have linked to a fiddle with code that replicates the problem. 

``` javascript
       // form validator initiate 
    jQuery.validate({
      form : '#well-wishes',
      addSuggestions: false,
      showHelpOnFocus: false,
      errorMessagePosition: 'inline',
      validateOnBlur: true,
      inlineErrorMessageCallback: function(input, errorMessage, conf) {
        createErrorPopup(input, errorMessage); 
      },
      modules: 'security, toggleDisabled'
    });
```

``` javascript
function createErrorPopup(input, errorMessage){ 
    console.log('error message:'+ errorMessage + '\n'+ 'Log triggered on: inlineErrorMessageCallback'); 
    var container = input.parent(); 
    if(container.hasClass('has-error')){
        console.log(container);
        msg = '<span class="help-block form-error"><p>'+errorMessage+'</p></span>';
        container.append(msg);
    }
```

Here is my attached fiddle. [https://jsfiddle.net/fm251pLp/](https://jsfiddle.net/fm251pLp/)

**Comment by konohanaruto** [comment]
**Yes, I have encountered the same problem, will the current bug fix it?**

**Here is my input:**

`<input class="col-12" type="text"  data-validation="required check_special_length" data-custom-length="4-24" data-validation-error-msg-required="username can not blank" id="username" name="username" value="" placeholder="username">`

**Here is my javascript code:**

`$(function () {
            $.formUtils.addValidator({
                name : 'check_special_length',
                validatorFunction : function (value, el, config, language, form) {
                    var usernameLength = getStringLength(value);  //This is a introduced custom function
                    var ranges = el.data('custom-length').split('-');
                    var minLength = ranges[0];
                    var maxLength = ranges[1];
                    if (usernameLength < minLength || usernameLength > maxLength) {
                        return false;
                    }
                },
                errorMessage : 'username length should be within 2-12 range',
                errorMessageKey: 'check_special_length_error'
            });

            $.validate({
                form : '#register_step_one',
                inlineErrorMessageCallback: function (input, errorMessage, config) {
                    console.log(errorMessage);
                    if (errorMessage) {
                        singleErrorMessages(input, errorMessage, config);
                    } else {
                        singleRemoveErrorMessages(input);
                    }
                    return false;
                },
                submitErrorMessageCallback: function (form, errorMessages, config) {
                    return false; // prevent default behaviour
                },
                onSuccess : function(form) {
                    return true; // Will stop the submission of the form
                }
            });
        });

        function singleErrorMessages(item, errorMessage, config)
        {
            var inputElementName = item.attr('name');
            var currentElementObject = $("input[name="+inputElementName+"]");
            var currentElementParentObject = currentElementObject.parent();
            currentElementParentObject.children('.text-icon-tips-incorrect').addClass('on');
            currentElementParentObject.find('.text-error-tips').html(errorMessage);
        }

        function singleRemoveErrorMessages(item)
        {
            var inputElementName = item.attr('name');
            var currentElementObject = $("input[name="+inputElementName+"]");
            var currentElementParentObject = currentElementObject.parent();
            currentElementParentObject.children('.text-icon-tips-correct').addClass('on');
            currentElementParentObject.children('.text-icon-tips-incorrect').removeClass('on');
        }`


Each time when the loss of focus, always prompt twice, one is the error message I need, and the other is always false, but my form has been able to submit a normal, that is, all through the verification, I do not know the false Always as the value of errorMessage is output, which in the end how is it?

@victorjonsson

**Comment by victorjonsson** [comment]
If the variable `errorMessage` is falsy you should remove the error message.
```js
 inlineErrorMessageCallback:  function($input, errorMessage, config) {
     if (errorMessage) {
      displayInlineErrorMessage($input, errorMessage);
     } else {
       removeInlineError($input);
     }
     return false; // prevent default behaviour
  }
```
Don't know if this was missing from the documentation at the time this issue was reported.
