### ISSUE TITLE
Browserify cannot “require” jquery-form-validator

### ISSUE THREAD

**Issue by diyinhaitang** [victorjonsson/jQuery-Form-Validator#517]
I use Browserify to require jquery-form-validator into .js files. After compile the .js file, however, the browser always report an error that "$.validate( ) is not a function".
I also tested that the jquery-form-validator really works when I inserted it into html file not compiled by browserify.
Does anyone has solutions to this propblem?

**Comment by diyinhaitang** [comment]
I use Browserify to require jquery-form-validator into .js files. After compile the .js file, however, the browser always report an error that "$.validate( ) is not a function".
I also tested that the jquery-form-validator really works when I inserted it into html file as <script src="path/to/jquery.form-validator.min.js">.
Does anyone has solutions to this propblem?

**Comment by dauble** [comment]
I had this same problem. I discovered there was a 'node_modules' folder with jQuery 3.1 contained within. My project was already including jQuery, causing a conflict. Once I removed the node_modules folder from my project's '/node_modules/jquery-form-validation/' folder and recompiled, the forms started validating properly.

**Comment by amorphine** [comment]
same issue

**Comment by victorjonsson** [comment]
I need more info on how to reproduce the error when it's not working.

I can not reproduce this error when going about it the following way:

1. Create empty project directory
2. Add package json with `dependencies: {"jquery-form-validator"}` and run npm-install
3. Adding js file with the following code 
```js
var jQuery = require('jquery'), 
f = require('jquery-form-validator');
console.log(jQuery.validate);
```
4. Running `browserify test.js -o bundle.js`
5. Including the file bundle.js in an html-file 

When opening the html-file in a browser, the console shows that the validate function provided by the plugin is present.

**Comment by victorjonsson** [comment]
I need more to go on here. I'll open this issue again if someone provides me with more detailed information.
