### ISSUE TITLE
Form with invalid inputs still submits

### ISSUE THREAD

**Issue by matteo1990** [victorjonsson/jQuery-Form-Validator#520]
Hello,
I'm having some issues with a form validation. When typing, i.e., some invalid characters, my _data-validation-error-msg_ is correctly displayed. Yet when I click the submit button, the form submits. 

Here is my relevant html:
```
<form method="post" action="" id="contact_form">
     <input type="text" class="form-control" data-validation="letternumeric" data-validation-allowing="-' " name="name"  required />
     <input type="submit" id="contact_button" class="btn btn-primary" action="submit" value="INVIA"/>
</form>
```

and here is my scripts:

```
<script src="plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script type="text/javascript" src="plugins/form-validator/jquery.form-validator.js"></script>
<script>
$.validate({
	modules:'security.dev, html5',
	validateOnBlur : true
});

</script>`
```

I've also tried with just

```
<script>
    $.validate();
</script>
```

and some simplier data-validations (with no modules needed), with no results.

Thank you.

**Comment by victorjonsson** [comment]
What version of the plugin are you using?

**Comment by victorjonsson** [comment]
I'm not able to reproduce this error. Works here as expected http://jsbin.com/zitokamaje/edit?html,js,console,output

**Comment by matteo1990** [comment]
thanks for your answer. I'm using the latest version avaible here on your github page. 
Is it possible, as far as you know, that my jquery version (2.1.4) conflicts with your plugin?
 
Now I'm trying with the same cdn as you:

```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js">
```
But here is what happens:

with 

```
$.validate({
	modules:'security.dev, html5',
	validateOnBlur : true
});
```
form is NEVER submitted.

and with

```
$.validate({
	modules:'security, html5',
	validateOnBlur : true
})
```

form is ALWAYS submitted.


Thank you.

**Comment by victorjonsson** [comment]
`security.dev` is not supported any more.

What do you mean by "always submitted" is that the expected behaviour.  My jsbin example works as expected, so I need a code example that reproduces the bug.

**Comment by matteo1990** [comment]
Ok, my issue has been resolved. 
It seems that a _data-validation-allowing_ with a '.' (dot) between its allowed characters caused the whole form to not work properly. This sounds a bit odd to me, but once removed everything started to be fine.
By the way thank you very much for your help Victor!
