### ISSUE TITLE
Server-site validation too slow because synchronised

### ISSUE THREAD

**Issue by clockover** [victorjonsson/jQuery-Form-Validator#521]
Hello,

If I enter quickly a text in a input with server validation some characteres are skipped because the validation is synchronised and on every keyup.

Is-it possible to use asynchronised mode or validate on unfocus event of the input ?

Thanks

**Comment by victorjonsson** [comment]
Well, it is async indeed... I'm guessing you have set `validateOnEvent: 'keyup'`?

**Comment by clockover** [comment]
No I just initialize jQuery Form validator with:

`$.validate({
	lang : 'fr', // (supported languages are fr, de, se, sv, en, pt)
	modules : 'toggleDisabled security'
});`

And the input:
`<input class="required input-block-level" id="user_email" name="email" type="text" data-validation="server" data-validation-url="<?= WEBSITE_FQDN ?>/?ajax&emailcheck" />`

So I think use the default options.

**Comment by victorjonsson** [comment]
Then that's really strange. The validation is not triggered on keyup and the http request surely [isn't made synchronous](#https://github.com/victorjonsson/jQuery-Form-Validator/blob/master/src/modules/security.js#L361).

**Comment by clockover** [comment]
Ok.
I will try with all other jquery plugin disabled maybe a conflict ?

**Comment by victorjonsson** [comment]
Okey. After testing this out I have found that you can trigger the validation onkeyup if you first enter something in the input and then blur the input followed by immediately stepping back to the input and start writing while the server is being requested. It is till made async though. 

Maybe a solution would be to disable the input while the server is being requested?

**Comment by clockover** [comment]
I am sorry, I don't understand very well this part: "and then blur the input followed by immediately stepping back to the input and start writing while the server is being requested. It is till made async though. "

I don't want to disable the input during the server's request, this is not very ergonomic.

With others plugins I have always the issue. 
I just use jQuery 3.1.1, bootstrap 3.3.7 and form-validator 2.3.44.

But I found the the issue of requesting the server on each keyup is causing by the toggleDisabled module. If I remove it, the server is requested only after filling the input.

(sorry for my English)

**Comment by victorjonsson** [comment]
That is the expected behaviour by toggleDisabled module. You want the submit button become enabled as soon as the form enters a valid state.
