### ISSUE TITLE
jshint file missing from repo

### ISSUE THREAD

**Issue by kontur** [victorjonsson/jQuery-Form-Validator#522]
Presumably there should be a jshint file present in the repo that ensures coding style conformity.

When running `$ grunt test` I get:

```
Johanness-MacBook-Pro:jquery-form-validator johannes$ grunt test
Running "concat:main" (concat) task
File ./form-validator/jquery.form-validator.js created.
File ./form-validator/jquery.form-validator.min.js created.

Running "copy:main" (copy) task
Created 2 directories, copied 30 files

Running "umd:main" (umd) task

Running "cssmin:target" (cssmin) task
>> 1 file created. 63.83 kB → 62.53 kB

Running "jshint:files" (jshint) task
ERROR: Can't find config file: .jshintrc
```

With the jshint file missing specified in `Gruntfile.js` l. 76

**Comment by victorjonsson** [comment]
That's strange since the [.jshintrc](https://github.com/victorjonsson/jQuery-Form-Validator/blob/master/.jshintrc) file is present in the repo.

**Comment by kontur** [comment]
Ah sorry, my bad. I just wanted to quickly hack one thing and did so straight into a copy that was installed via bower. And that type of install, apparently, doesn't have the jshint - it probably gets stripped somewhere from the repo for distribution through bower?
