### ISSUE TITLE
On loading module got JS error "TypeError: a.formUtils is undefined" in file.js

### ISSUE THREAD

**Issue by mjunaidtheleo** [victorjonsson/jQuery-Form-Validator#529]
I need to validate file upload for images and when i try to load module(file or any other) I got this error
"TypeError: a.formUtils is undefined"

```js
$.validate({
        form : '#brand_form',
        modules : 'file',
        borderColorOnError : 'red',
        inputParentClassOnError : 'error',
        scrollToTopOnError: true,
        errorMessageClass: 'text-error',
        onError : function() {
        },
        onSuccess: function($form) {
            // The input button is disabled if the form contains backend validations
            $form.find('input[type="submit"]').unbind('click');
            return true;
        }
    });
```

Can you please let me know what am I doing wrong?

**Comment by victorjonsson** [comment]
This means that you have called `$.validate` before the script have been included on the page

**Comment by mjunaidtheleo** [comment]
Thanks victor for you reply 
I just placed the `$.validate`  under the jquery.form-validator.min.js but still not working for me.
Do I need to include any other file or use some other version of Jquery (Currently I am using v1.10.2).
I know I am doing some stupid mistake. Please help.
Thanks Victor,

**Comment by victorjonsson** [comment]
Have you included the jquery-script before you include the form-validator script? Could you provide me with you markup?

**Comment by mjunaidtheleo** [comment]
Thanks victor for the help.
The problem is fixed now. I was actually including the Jquery Script in the footer section. 
Fixed now!
