### ISSUE TITLE
toggleDisabled and server-side validation

### ISSUE THREAD

**Issue by Svarok** [victorjonsson/jQuery-Form-Validator#530]
Hi!

Server-side validation is triggered every time a key is pressed and the input field loses focus with error.

![firebug - 2016-11-11 15 02 53](https://cloud.githubusercontent.com/assets/7721869/20214581/2b7cafde-a820-11e6-80d5-ea0e0dda2e33.png)

**Comment by Svarok** [comment]
Form validator: 2.3.26

**Comment by victorjonsson** [comment]
You want the submit button to become enabled as soon as the form is valid, hence you want the module to validate the inputs on keyup. This have been discussed several times before. 

In other words, you can't combine toggleDisabled with server side validation.
