### ISSUE TITLE
IE8 issue

### ISSUE THREAD

**Issue by grun** [victorjonsson/jQuery-Form-Validator#537]
Any solutions to make it works in IE8?
The errors are: 
1) 'lang' is null or not an object.
2) Invalid range in characters set

**Comment by victorjonsson** [comment]
Are you using any modules?

**Comment by grun** [comment]
The second error appears even on demo pages (/test/form.html)

**Comment by victorjonsson** [comment]
This should now be fixed (notice that you can't run test/*.html files unless you manually edit the version jQuery being used on page)
