### ISSUE TITLE
Server-side validation triggers immediately onchange

### ISSUE THREAD

**Issue by johnomorales** [victorjonsson/jQuery-Form-Validator#543]
There's an issue on server-side validation, it fires server-side checking immediately as you type 1 character on the textfield,

to make this issue less annoying, I added length validation with min4.

but it's still there. after 4 characters it will trigger the server-side checking.

`
<input type="text" id="referrer" name="referrer"
				placeholder="Enter referrer" data-validation="length server"
				data-validation-length="min4" data-validation-optional="true" data-validation-url="<myurl>">
`

The weird part is that, after the initial check (after 4 characters then server-side checking)

the server-side validation on that textfield works properly..
and will only trigger after I press "Tab"

Any workaround? fix? or anything I'm missing?

Thanks.

**Comment by victorjonsson** [comment]
How does your setup configuration look like? What you're describing is not the expected behaviour. What version of the plugin are you using?

**Comment by johnomorales** [comment]
@victorjonsson 

Thank you for your immediate response.

I'm using

jquery-3.1.0
jquery.form-validator (latest - where the possible bug still exist.)

Here's a JS fiddle. (using external resource same as (http://www.formvalidator.net/))

https://jsfiddle.net/xbatusayx/fbfd16yu/10/

Type: jomorales
on the referrer textbox for a valid response.

The problem is more noticeable on JSFiddle, server checking is firing every 1-2 characters, this is a problem when you're working with CORS.

**Comment by victorjonsson** [comment]
#530
