### ISSUE TITLE
data-validation-req-params submit bug

### ISSUE THREAD

**Issue by johnomorales** [victorjonsson/jQuery-Form-Validator#556]
`<input id="email" name="email" type="email" data-validation="required email server" data-validation-url="https://www.domain.com/availability/check" data-validation-req-params="{"oldEmail":"myemail@yahoo.com"}" disabled="disabled">

$.validate({ modules : 'date , security' });

It works fine, if I trigger/validate/edit the field with (data-validation-req-params) manually first, this means that I have to trigger the (Green Check Icon), 

However the submit issue bug comes when, I submit before editing/validating the field with data-validation-req-params,

 It's messing up my POST method. (turning it to a GET)

Observed:

During manual validation / edit 
AJAX POST
URL = domain/profile

If Not Triggered.
Page re-submits with
URL = domain/profile?field1=field1Value&field2=field2Value&...N times

**Comment by johnomorales** [comment]
Additional,

It seems to be a race condition in conflict with

$("#formName").isValid()

**Comment by victorjonsson** [comment]
Could you tell me what the js error console says when the form gets re-submitted?

btw, the methos `isValid` does not support async validators such as the server validation 

> Notice! This method won't be able to tell if the form is valid if your'e using asynchronous validators, like the server-side validator and the image dimensions validator. In such a case you must combine the method call with the onSuccess callback.

http://www.formvalidator.net/#advanced_programmatically

**Comment by victorjonsson** [comment]
Let me know if you're still getting erroneous behaviour from the plugin.

**Comment by johnomorales** [comment]
@victorjonsson -

I no longer have an issue, but I'm using a workaround, and triggering change event manually.

`$("#email").trigger("change");`

for the data-validation-req-params

Was this fixed already? i haven't versioned up.

**Comment by victorjonsson** [comment]
Well, I need to see more code. The example code you have in the beginning of your post doesn't make any sense since disabled inputs won't become validated.

I'm not able to reproduce this bug with the information you're giving me. Here you can see a working example: http://jsbin.com/vinozawipe/edit?html,output
