### ISSUE TITLE
Always have the error element displayed

### ISSUE THREAD

**Issue by ikOrbis** [victorjonsson/jQuery-Form-Validator#558]
Hello,

Is it possible to always have the error span element displayed even if it doesn't have any values? The reason is because the form expands after a value is not filled in, to display the error message.
`<span class="help-block form-error">This is a required field</span>`

Kindly let me know.

Cheers.
Iram

**Comment by victorjonsson** [comment]
You could achieve something like this if you take care of the error dialogs yourself. 

http://www.formvalidator.net/#configuration_position
