### ISSUE TITLE
Error JS with other script

### ISSUE THREAD

**Issue by jbustamanterendon** [victorjonsson/jQuery-Form-Validator#570]
Hello,

We have your script in a project where it is including this javascript "https://secure.mlstatic.com/org-img/checkout/custom/1.0/checkout.js" and causes a problem.

> "module  is not defined"

The solution is apply a double validation on:
`"object"==typeof exports?module.exports=b`

this way:
`"object"==typeof exports && "object"== typeof module ? module.exports=b`

Best regards.

**Comment by victorjonsson** [comment]
This no longer seem to be an issue.
