### ISSUE TITLE
disabledFormFilter is not filtering anything

### ISSUE THREAD

**Issue by samurdhilbk** [victorjonsson/jQuery-Form-Validator#573]
Is there a way to enable the toggleDisabled option only on specified forms and disabled if not specified explicitly?

**Comment by samurdhilbk** [comment]
I tried 
```
$.validate({
  modules : 'toggleDisabled',
  disabledFormFilter : 'form.toggle-disabled'
});
```

as specified in the web-page under the advanced section. I added a class `toggle-disabled` to all the forms I need to enable the `toggleDisabled` feature and called the above on page-ready. But it is enabling `toggleDisabled` on all forms, even ones without the class `toggle-disabled`. Why is that? What am I doing wrong?

**Comment by victorjonsson** [comment]
What version of the plugin are you using? I'm not able to reproduce this bug http://jsbin.com/xizexineko/edit?html,js,output
