### ISSUE TITLE
Form element validates but form does not.

### ISSUE THREAD

**Issue by JessycaFrederick** [victorjonsson/jQuery-Form-Validator#590]
[I asked this on StackOverflow](http://stackoverflow.com/questions/43750323/jquery-form-validator-js-form-input-validates-but-form-itself-fails-validation) but I'm not getting any help there.

I have a form with one field, email. When the input loses focus, the field validates correctly and reports to the console. When the user then clicks submit, the alert for the onError event pops up saying the form isn't valid.

I don't understand what's not valid. Is there a way to get the specific problem to be displayed either in the alert or the console? Thank you.

**Comment by victorjonsson** [comment]
You have the answer on stackoverflow
