### ISSUE TITLE
Problems with data-validation-optional-if-answered

### ISSUE THREAD

**Issue by ErickRdz** [victorjonsson/jQuery-Form-Validator#593]
Hello Victor and everyone! 

I´m trying to require only one out of several inputs in a form (a cellphone number or an email at least) using the login module and the attribute "data-validation-optional-if-answered" but it doesn´t work for me because it requires me these two fields. 

This is my HTML code:
```html
<div>
	<label for="inputName" class="control-label">Email: *</label>
	<input type="text" class="form-control text-keyboard" id="ce_email" name="ce_cellphone" placeholder="Ej: pepe@mail.com" data-validation="email" data-validation-optional-if-answered="ce_cellphone" >
</div>
<div>
	<label for="inputName" class="control-label">Celular:</label>
	<input type="text" class="form-control num-keyboard" id="ce_cellphone" name="ce_cellphone" placeholder="Ej: 8115141311" data-validation="number" data-validation-optional-if-answered="ce_email">
</div>
```

And this is my Javascript code to configure the plugin:

```js
  conf = {
    onElementValidate : function(valid, $el, $form, errorMess) {
      if( !valid ) {
       // gather up the failed validations
       errors.push({el: $el, error: errorMess});
      }
    }
  };

  lang = {};

  $.formUtils.loadModules('security, date, logic');
```

I'm using the version 2.3.61 of the plugin

**Comment by ErickRdz** [comment]
This is my HTML code:

`<div>
<label for="inputName" class="control-label">Email: *</label>
	<input type="text" class="form-control text-keyboard" id="ce_email" name="ce_cellphone" placeholder="Ej: pepe@mail.com" data-validation="email" data-validation-optional-if-answered="ce_cellphone" >
</div>

<div>
<label for="inputName" class="control-label">Celular:</label>
	<input type="text" class="form-control num-keyboard" id="ce_cellphone" name="ce_cellphone" placeholder="Ej: 8115141311" data-validation="number" data-validation-optional-if-answered="ce_email">
</div>`

**Comment by ErickRdz** [comment]
This is my HTML code:

{div}
	{label for="inputName" class="control-label"}Email: *{/label}
	{input type="text" class="form-control text-keyboard" id="ce_email" name="ce_cellphone" placeholder="Ej: pepe@mail.com" data-validation="email" data-validation-optional-if-answered="ce_cellphone" }
{/div}

{div}
	{label for="inputName" class="control-label"}Celular:{/label}
	{input type="text" class="form-control num-keyboard" id="ce_cellphone" name="ce_cellphone" placeholder="Ej: 8115141311" data-validation="number" data-validation-optional-if-answered="ce_email"}
{/div}

**Comment by ErickRdz** [comment]
This is my HTML code:

{div}
{label for="inputName" class="control-label"}Email: *{/label}
{input type="text" class="form-control text-keyboard" id="ce_email" name="ce_email" placeholder="Ej: pepe@mail.com" data-validation="email" data-validation-optional-if-answered="ce_cellphone" }
{/div}

{div}
{label for="inputName" class="control-label"}Celular:{/label}
{input type="text" class="form-control num-keyboard" id="ce_cellphone" name="ce_cellphone" placeholder="Ej: 8115141311" data-validation="number" data-validation-optional-if-answered="ce_email"}
{/div}

**Comment by victorjonsson** [comment]
Should I assume that you have a call  `$.validate(conf)` in you js code? Why are you loading the modules manually?

**Comment by victorjonsson** [comment]
When I made a jsbin with you code I noticed you had forgotton to name the first input "ce_email", that is your only problem, as long as your not doing any crazy thing with your setup code

http://jsbin.com/gufugitohe/edit?html,output
