### ISSUE TITLE
validate fields generated after document load

### ISSUE THREAD

**Issue by AurelDragut** [victorjonsson/jQuery-Form-Validator#596]
Hey, i need some help with validating form fields that are generated after document is completely loaded.

i am thinking about something like 
```
$(document).on("mouseleave", "textarea.comment", function () {
}
``` 
and 
```
$(document).on("submit", "form.comments", function () {
}
```

its just i dont know how to do it...

**Comment by victorjonsson** [comment]
You can call `$.validate` at any time. Multiple calls works fine as well.

**Comment by AurelDragut** [comment]
Thanks, i tried something like
```
$(document).on("mouseleave", "textarea.answer-comment", function () {
        $(this).validate(function(valid, elem) {
            console.log('Element '+elem.name+' is '+( valid ? 'valid' : 'invalid'));
        });
    });
``` 
but i get the error ``` Cannot read property 'nodeType' of undefined ``` and the element is valid (i can read any of its attributes). Is there something that i am missing? Thx.

**Comment by AurelDragut** [comment]
Nevermind, now i understood what you said and i got it working. Thanks!
