### ISSUE TITLE
Validate form within modal

### ISSUE THREAD

**Issue by BigIWT** [victorjonsson/jQuery-Form-Validator#608]
Hi
I have a form page which is opened within a modal, but can't seem to get the validation to work.
eg
Form within on page modal - validation works
Form called from another page, into a generic modal - validation doesn't work.

Any ideas how to proceed?
thanks

**Comment by victorjonsson** [comment]
Need to see your code, otherwise I'm not able to help you.

**Comment by BigIWT** [comment]
Scratch that, I've located the source of my problem which relates to using maxlength within an input - I've raised another question.
