### ISSUE TITLE
internet explorer problem

### ISSUE THREAD

**Issue by vijayarajmahendran** [victorjonsson/jQuery-Form-Validator#613]
https://jsfiddle.net/28tfq1dn/..

please check the following link in IE browser . After validating there is small error icon this only occur in microsoft edge and IE . Any solution for this problem?

**Comment by victorjonsson** [comment]
Do you mean the black cross? https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs
