### ISSUE TITLE
data-validation="size" Error Maybe you have forgotten to load the module that validate_size

### ISSUE THREAD

**Issue by metalbox** [victorjonsson/jQuery-Form-Validator#625]
Hi, When i try this rule data-validation="size"

The console show this error 

> Error: Using undefined validator "validate_size". Maybe you have forgotten to load the module that "validate_size" belongs to? jquery.form-validator.min.js:9:15162

I try this

```
jQuery.validate({
  modules : 'date, security, validate_size',
  onModulesLoaded : function() {
    alert('All modules loaded!');
  }
});
```

But nothing happen

**Comment by metalbox** [comment]
well, now i loaded file.js 

```
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script type='text/javascript' src='http://localhost/wp/wp-content/themes/shop/js/file.js?ver=4.8'></script>
```

but now show this error

> $.formUtils.registerLoadedModule is not a function

**Comment by victorjonsson** [comment]
The size validator is part of the file module.

```js
jQuery.validate({
  modules : 'date, security, file'
});
```
