### ISSUE TITLE
isValid returns true but submit returns validation errors

### ISSUE THREAD

**Issue by AurelDragut** [victorjonsson/jQuery-Form-Validator#635]
Hello, 

I have an `<a>` tag as 'submit button' for a form, when i check form.isValid this tag changes according to the return of isValid, but i got the issue that isValid returns true, the button becomes valid due to my changes and when i push the button it returns validation errors. What can i do?

the validation rules are added inline to the input tags, should i pass any parameters to isValid in this case?

**Comment by victorjonsson** [comment]
Are you using any async validators?

**Comment by AurelDragut** [comment]
No, sorry i forgot to close the issue. The problem was that i didn't add a configuration as a parameter to the isValid method, i fixed that and its working now. Thanks!
