### ISSUE TITLE
Duplicate error message when button is click multiple times

### ISSUE THREAD

**Issue by 3ncor3** [victorjonsson/jQuery-Form-Validator#636]
Hi,

When  I click the submit button multiple times then the error message will duplicate. How to fix this issue?

update : using jQuery v3.2.1

Thank you

![untitled-1](https://user-images.githubusercontent.com/2099950/29998488-c063a068-905e-11e7-9ffa-f486fe5ca8ff.jpg)

```javascript
$('#someButton').click(function(){
$.validate({
  form : '#frmDaftar',
  modules:"security",
  errorElementClass:"is-invalid",
  borderColorOnError:"",
  errorMessageClass:"invalid-feedback m-0 p-0",
  onSuccess : function() {		
        //triggger ajax
        return false;
    }
  
});
});
```

**Comment by 3ncor3** [comment]
Well, it seems no answer to my question but I manage to do a "quick and dirty" fix. 

Just use the ```beforeValidation``` event to remove the ```<span class="help-block">``` element everytime the validation is initiate. 

```
 $('#form).on('beforeValidation', function() {
      $("span.help-block").remove();
    });	
```

Its work only when the submit button is clicked (no error message repeat) but it's still repeat on form blur validation event.

**Comment by victorjonsson** [comment]
One problem with your setup code is that you apply it every time the button is clicked. The setup function is only supposed to run once.

**Comment by 3ncor3** [comment]
Can you explain a bit more @victorjonsson perhaps with example

**Comment by victorjonsson** [comment]
Remove the part where you attach a callback function to the button click event `$('#someButton').click` 
It should only be:

```js
$.validate({
  form : '#frmDaftar',
  modules:"security",
  errorElementClass:"is-invalid",
  borderColorOnError:"",
  errorMessageClass:"invalid-feedback m-0 p-0",
  onSuccess : function() {		
        //triggger ajax
        return false;
    }
});
```

**Comment by 3ncor3** [comment]
Yeah, my mistake.  The button click event is unnecessary.

Thanks @victorjonsson!

**Comment by victorjonsson** [comment]
The problem is that you have applied multiple classes in `errorMessageClass`. Only a single class name is supported.

**Comment by Korsario23** [comment]
> One problem with your setup code is that you apply it every time the button is clicked. The setup function is only supposed to run once.

Yes. It was my issue. Thanks!!!

**Comment by anmol645** [comment]
<img width="1913" height="997" alt="Image" src="https://github.com/user-attachments/assets/e6738010-2261-49be-b446-ea1441ce3806" />
<img width="1904" height="996" alt="Image" src="https://github.com/user-attachments/assets/78e9f5d3-fee7-41ce-a4df-70f77e76f088" />
<img width="1927" height="1011" alt="Image" src="https://github.com/user-attachments/assets/f4b40c47-be34-46a4-9bed-83c90149e46f" />


same problem please solve my problem bro

<img width="1895" height="876" alt="Image" src="https://github.com/user-attachments/assets/d73e247b-9756-4530-90c3-c00ebcd0f742" />

visit my site
==================================
https://prismatic-crumble-49ab7a.netlify.app/
==================================


`var errormessage = "";
var missingfeild = "";
function isEmail(email) {
    var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    return regex.test(email);
}


$("#submitbutton").click(function () {
    if ($("#Email").val() == "") {
        missingfeild += "<p>Email not filled</p>";
    }
    if ($("#phoneno").val() == "") {
        missingfeild += "<p>Phone number not filled</p>";
    }
    if ($("#password").val() == "") {
        missingfeild += "<p>Password is not filled"
    }
    if (isEmail($("#Email").val()) == false) {
        errormessage += "<p>email id is not valid</p>";
    }
    if ($.isNumeric($("#phoneno").val()) == false) {
        errormessage += "<p>Phone number is not valid</p>";
    }
    if ($("#password").val() != $("#confirmpassword").val()) {
        errormessage += "<p>password does not match </p>";
    }
    if (errormessage == "") {
        $("#success").html("you are registered")
    } else {
        $("#errors").html(errormessage + missingfeild);
    }
});
// form password all validation 
var myInput = document.getElementById("password");
var letter = document.getElementById("letter");
var capital = document.getElementById("capital");
var number = document.getElementById("number");
var length = document.getElementById("length");

// When the user clicks on the password field, show the message box
myInput.onfocus = function () {
    document.getElementById("message").style.display = "block";
}

// When the user clicks outside of the password field, hide the message box
myInput.onblur = function () {
    document.getElementById("message").style.display = "none";
}

// When the user starts to type something inside the password field
myInput.onkeyup = function () {
    // Validate lowercase letters
    var lowerCaseLetters = /[a-z]/g;
    if (myInput.value.match(lowerCaseLetters)) {
        letter.classList.remove("invalid");
        letter.classList.add("valid");
    } else {
        letter.classList.remove("valid");
        letter.classList.add("invalid");
    }

    // Validate capital letters
    var upperCaseLetters = /[A-Z]/g;
    if (myInput.value.match(upperCaseLetters)) {
        capital.classList.remove("invalid");
        capital.classList.add("valid");
    } else {
        capital.classList.remove("valid");
        capital.classList.add("invalid");
    }

    // Validate numbers
    var numbers = /[0-9]/g;
    if (myInput.value.match(numbers)) {
        number.classList.remove("invalid");
        number.classList.add("valid");
    } else {
        number.classList.remove("valid");
        number.classList.add("invalid");
    }

    // Validate length
    if (myInput.value.length >= 8) {
        length.classList.remove("invalid");
        length.classList.add("valid");
    } else {
        length.classList.remove("valid");
        length.classList.add("invalid");
    }
}

// password show / hide function 
function myFunction() {
    var x = document.getElementById("password");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
    var x = document.getElementById("confirmpassword");
    if (x.type === "password") {
        x.type = "text";
    } else {
        x.type = "password";
    }
}`
