### ISSUE TITLE
Maxlength attribute overrides the data-validation-length attribute

### ISSUE THREAD

**Issue by etcho** [victorjonsson/jQuery-Form-Validator#658]
I was trying to use `data-validation="required length" data-validation-length="1000-2000" maxlength="2000"`. After hitting my head on the wall for several minutes, I inspected the generated HTML and the `data-validation-length` attributes was setted to "max2000". Removing the maxlength attribute make it work.

Is it ok for maxlength to override the data-validation-length?

**Comment by victorjonsson** [comment]
Why do you need to combine maxlength and data-validation-length? Wouldn't it be enough to only use data-validation="required length" and leave out the max-length attribute?

**Comment by etcho** [comment]
Well, I have to agree that it works. I was just trying to be extra careful since the form's users are wild beings. But, yes. It will do it.
