### ISSUE TITLE
Confirmation not working in last version

### ISSUE THREAD

**Issue by decosvaldo** [victorjonsson/jQuery-Form-Validator#659]
Using version 2.3.77

I'm working with Bootstrap 4. The password length verification is working fine, but the error message for not matching passwords are not showing.

My code:

<div class="md-form form-sm d-none" id="divnewpassword" name="divnewpassword">
									<i class="fa fa-lock prefix"></i>
									<input type="password" id="newpassword" name="newpassword" class="form-control" data-validation="length" data-validation-length="min6" data-validation-error-msg="Ops... a senha deve possuir ao menos 6 caracteres" data-validation-error-msg-container="#password-error-dialog">
									<label for="newpasword">Sua nova senha:</label>
									<p class="red-text" id="password-error-dialog"></p>
								</div>
				
								<div class="md-form form-sm d-none" id="divconfirmnewpassword" name="divconfirmnewpassword">
									<i class="fa fa-lock prefix"></i>
									<input type="password" id="confirmnewpassword" name="confirmnewpassword" class="form-control" data-validation="confirmation" data-validation-confirm="newpassword" data-validation-error-msg="Ops... as senhas diferem" data-validation-error-msg-container="#password-dont-match-dialog">
									<label for="confirmnewpassword">Confirme:</label>
									<p class="red-text" id="password-dont-match-dialog" name="password-dont-match-dialog"></p>
								</div>

Thanks..

**Comment by decosvaldo** [comment]
Here is the full code

									<input type="password" id="newpassword" name="newpassword" class="form-control" data-validation="length" data-validation-length="min6" data-validation-error-msg="Ops... a senha deve possuir ao menos 6 caracteres" data-validation-error-msg-container="#password-error-dialog">
									<label for="newpasword">Sua nova senha:</label>
									<p class="red-text" id="password-error-dialog"></p>

				
								
									<input type="password" id="confirmnewpassword" name="confirmnewpassword" class="form-control" data-validation="confirmation" data-validation-confirm="newpassword" data-validation-error-msg="Ops... as senhas diferem" data-validation-error-msg-container="#password-dont-match-dialog">
									<label for="confirmnewpassword">Confirme:</label>
									<p class="red-text" id="password-dont-match-dialog" name="password-dont-match-dialog"></p>

**Comment by victorjonsson** [comment]
This plugin is not compliant with bootstrap 4 at the moment.

**Comment by BrianHo888** [comment]
Any update to make this plugin compliant with bootstrap 4 and jquery 3.31?

**Comment by victorjonsson** [comment]
No real plans but I consider it rather urgent...
