### ISSUE TITLE
Uncaught Error: reCaptcha API can not be loaded by hand, delete reCaptcha API snippet.

### ISSUE THREAD

**Issue by sidbenac** [victorjonsson/jQuery-Form-Validator#712]
it looks like when instantiating the security module, I am getting this error in the console. any idea ?

here's my code, what I am doing wrong ?
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.77/jquery.form-validator.min.js" type="text/javascript"></script>

$.validate({
  validateHiddenInputs: true,
  form: '#configure',
  lang: 'en',
  modules: 'security'
});
here's the error :
![image](https://user-images.githubusercontent.com/8508974/43225740-e06f59e6-9027-11e8-8054-7260b36b3448.png)

**Comment by victorjonsson** [comment]
You can not have the google recaptcha initialisation present in the markup when loading the security model. You must configure recaptcha via jquery-form-validator.

http://www.formvalidator.net/index.html#security-validators_recaptcha

**Comment by sidbenac** [comment]
Got it, thx for the reply

**Comment by vqquoc** [comment]
I have problems like you, how to fix it?

**Comment by ADavidLiu** [comment]
Neither of the methods mentioned here are working for me: http://www.formvalidator.net/index.html#security-validators_recaptcha

Should that automatically add the reCaptcha widget?

**Comment by Ulrich-Mbouna** [comment]
> You can not have the google recaptcha initialisation present in the markup when loading the security module. You must configure recaptcha via jquery-form-validator.
> 
> http://www.formvalidator.net/index.html#security-validators_recaptcha

This link is no longer valid, how can I set google recaptcha validation with this jquery plugin? Thanks

**Comment by nick0488** [comment]
If you want to look at the documention on http://www.formvalidator.net/index.html#security-validators_recaptcha

Best way is to use the Way back Machine - and go to 2020 and you should see all the documentation

**Comment by victorjonsson** [comment]
https://web.archive.org/web/20200213221341/http://www.formvalidator.net/#security-validators_recaptcha
