### ISSUE TITLE
Unable to submit form what's wrong?

### ISSUE THREAD

**Issue by Shaz3e** [victorjonsson/jQuery-Form-Validator#719]
Hello,

When I click submit button the form is not submitting the data, here is my code please check and let me know if I am doing something wrong.

I am calling formvalidator script in head and custom script in footer

```
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="js/fontawecome.js"></script>
<script type="text/javascript" src="js/jquery.form-validator.min.js"></script>
```

**HTML**
<form method="POST" action="user-process" id="registrationForm">
	
	<div class="form-group row">
		<div class="col-6">
			<label for="name">Name</label>
			<input type="text" name="name" id="name" class="form-control" placeholder="Your Name" data-validation="length" data-validation-length="min3" data-validation-help="Please type your full name" data-validation-error-msg="Please type full name">
		</div>

		<div class="col-6">
			<label for="company" >Company</label>
			<input type="text" name="company" id="company" class="form-control" placeholder="XYZ Ltd" data-validation="length" data-validation-length="min4" data-validation-help="Please type your company name" data-validation-error-msg="Please type company name">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-12">
			<label for="email">Email</label>
			<input type="email" name="username" id="email" class="form-control" placeholder="name@xyzltd.com" data-validation="email" data-validation-help="This will be your username" data-validation-error-msg="Email is required">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-6">
			<label for="password">Password</label>
			<input type="password" name="passwd" id="password" class="form-control" placeholder="Random@123" data-validation-required="alphanumaric length" data-validation-allowing="~*!@$#%_+.?:,{})" data-validation-length="9-16" data-toggle="tooltip" data-placement="right" data-html="true" title="Must including the following<br><ul><li>1 lowercase character</li><li>1 uppercase character</li><li>1 number</li><li>1 special character: ~*!@$#%_+.?:,{})</li></ul>" aria-describedby="tooltipPassword" data-validation="required" data-validation="length" data-validation-length="9-16" data-validation="strength" data-validation-strength="2" data-validation-help="Password should contains 9 to 16 character long and must include 1 lowercase character, 1 uppercase character, 1 number and 1 special character ~*!@$#%_+.?:,{})" data-validation-error-msg="Password is required">
		</div>
		<div class="col-sm-6">
			<label for="confpass">Confirm Password</label>
			<input type="password" name="confPassword" id="confpass" class="form-control" placeholder="Repeat" data-validation="required" data-validation="confirmation" data-validation-confirm="passwd" data-validation-help="Confirm password should be same as password" data-validation-error-msg="Password does not match">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-6">
			<label for="phoneCC">Country Code</label>
			<input type="text" name="phone-cc" id="phoneCC" class="form-control" placeholder="1" data-validation="number" data-validation="length" data-validation-length="1-3" data-validation-help="Please provide country code" data-validation-error-msg="Country Code should contains only number and 1 to 3 digit long">
		</div>
		<div class="col-sm-6">
			<label for="phone">Phone No.</label>
			<input type="text" name="phone" id="phone" class="form-control" placeholder="0000000000" data-validation="length number" data-validation-length="5-20" data-validation-help="Please provide contact number" data-validation-error-msg="Phone number is required">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-12">
			<label for="address">Address</label>
			<input type="text" name="address-line-1" id="address" class="form-control" placeholder="Your Address" data-validation="required" data-validation-help="Please type your complete address" data-validation-error-msg="Address is required">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-6">
			<label for="country">Country</label>
			<select name="country" id="country" class="form-control" onchange="showStates(this.value)" data-validation="required" data-validation-help="Please select country from the list" data-validation-error-msg="Country is required">
				<option value="">Select Country</option>
				<option value="PK">Pakistan</option>
			</select>
		</div>

		<div class="col-sm-6">
			<div id="RecordedStates">
				<label for="states">State</label>
				<select name="state" class="form-control" id="states" data-validation="required" data-validation-help="Select state from the drop down if you not found your state in the list please select other option" data-validation-error-msg="State is required">
					<option value="">Select State</option>
					<option value="Other">Other</option>
				</select>
			</div>
		</div>

	</div>

	<div class="form-group row">
		<div class="col-sm-6">
			<label for="zip">Zip Code</label>
			<input type="text" name="zipcode" id="zip" class="form-control" placeholder="00000" data-validation="length number" data-validation-length="3-10" data-validation-help="Type your zip code" data-validation-error-msg="Zip code is required and must be digit">
		</div>

		<div class="col-sm-6">
			<label for="city">City</label>
			<input type="text" name="city" id="city" class="form-control" placeholder="Your City" data-validation="required" data-validation-help="Please type your city name" data-validation-error-msg="City is required">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-12">
			<input type="checkbox" id="tos" data-validation="required" data-validation-error-msg="You must agree to our terms of services before you create account">
			<label for="tos">
				<strong>By creating an account you agree to our <a href="#">Terms of Service, Cancellation Policy</a> and acknowledge receipt of the <a href="#">Privacy Policy</a>.</strong>
			</label>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-12">
			<button type="submit" name="register-customer" class="btn btn-success register-customer">Create Account</button>
		</div>
	</div>
</form>

**Custom JS**
_Calling it in footer in scripts.js file_
```
$.validate({
	form : '#registrationForm',
	modules : 'security, html5',
	onModulesLoaded : function() {
		var optionalConfig = {
			fontSize: '12pt',
			padding: '4px',
			bad : 'Very bad',
			weak : 'Weak',
			good : 'Good',
			strong : 'Strong'
		};
	$('#password').displayPasswordStrength(optionalConfig);
	}
});
```

**Comment by lalaithan** [comment]
Have you tried the method described in the second paragraph [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Cform%3E_element)? I don't see how your form data is being collected or where it's supposed to go when submitting.

**Comment by Shaz3e** [comment]
I quit
